### ISSUE TITLE
Add documentation on cluster issues

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#10]
There are a limited set of issues that can be presented in the UI, for example:

- Servers that should be removed from the cluster
- Metadata conflicts
- Redundancy issues
- Zombie servers

...and a few more. It would be useful to describe these different cases, and the consequences of resolving them (and would help simplify some error messages if we had a public resource for users to refer to).

**Comment by chipotle** [comment]
While we don't have an explicit "cluster issues" document, some of these things are covered in other places in the docs—and I'm not sure how much of what's here now still applies given that this is two and a half years old. If this is still relevant, please re-open a modern version of this ticket.
