### ISSUE TITLE
Wait, rebalance, reconfigure require explicit db or table

### ISSUE THREAD

**Issue by nighelles** [rethinkdb/docs#1004]
You can no longer call r.wait() without an explicit table or database selection.

r.wait(table) or r.table("blah").wait() is required now.

**Comment by chipotle** [comment]
re: the issue title, If it was possible to call `reconfigure` and `rebalance` without an explicit database or table selection, it doesn't appear it was ever documented, so I'm only changing the documentation for `wait`.

**Comment by danielmewes** [comment]
@chipotle I think we forgot document it because it's not something you'd usually want to do. At least that forgetfulness is paying out now :-)
