### ISSUE TITLE
Add some libraries to the 'third-party libraries' page

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#1007]
I received a note from @athlite about some RethinkDB libraries he's created -- should be added to the list of third-party-libraries.

> I just want to submit a few tools I've made with nodejs. I hope you will post them to your website, and that someone will find them useful.
> 
> https://github.com/athlite/rethinkdb-cli
> https://github.com/athlite/hapi-rethinkdb-crud
> https://github.com/athlite/rethinkdb-fixtures

**Comment by athlite** [comment]
Thanks @mglukhovsky

**Comment by chipotle** [comment]
I'll add `rethinkdb-cli` to the third party administration tool page (where other CLI/REPLs are) and the other two to the frameworks and libraries page.
