### ISSUE TITLE
Install page for Windows

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1011]
A few things we need to do for the Windows preview release:
* Add a button to the official packages on http://rethinkdb.com/docs/install/ . We should put a "Beta" badge on the button to signal that it's not fully production ready.
* Add an "Install RethinkDB on Windows" page, similar to http://rethinkdb.com/docs/install/osx/ . For now, we will simply provide a .zip file with a single .exe file inside. We should describe the process of unpacking it. In contrast to the other install pages, we should also describe briefly how to launch the server from the command line, as we're not adding any start menu icons yet as Windows users might expect.
* Provide build instructions on the same page, if people want to build from source. (@AtnNn can you write up the necessary pre-requirements and steps?)

@AtnNn @chipotle

**Comment by AtnNn** [comment]
Here are the latest build instructions:

https://github.com/rethinkdb/rethinkdb/blob/atnnn/windows2/WINDOWS.md
