### ISSUE TITLE
Note in write term API docs about error handling

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1018]
We handle failures in write operations (insert, delete, update, replace) differently from other errors. Often we don't throw an exception, but instead just return a value larger than 0 in the `errors` return value, and set `first_error`.

To cite @mlucy:
> the rule is that if an error occurs before any writes could plausibly have occured, the entire write is aborted, but if the error occurs on the shards we assume that other writes might be executing at the same time and instead populate `first_error`.  `.insert([errorDoc, okDoc])` fails before we get to the shards because the error occurs while constructing the array.  `.replace{|row| error}` fails on the shards because that's where the function is executing.

This has caused confusion for a number of users, for example https://github.com/rethinkdb/rethinkdb/issues/5395 .

I think we should add a well visible note to the API docs of those terms, that for correct error handling, users need to both handle exceptions and also check the `errors` return value.

**Comment by deontologician** [comment]
As a small bit of context for the above quote, the `errorDoc` he's referring to is something like `{foo: r.error('bar')}`, where upon evaluation it fails because of r.error. `okDoc` would just be any normal document.
