### ISSUE TITLE
Interleave optarg on union

### ISSUE THREAD

**Issue by nighelles** [rethinkdb/docs#1021]
```
union(..., interleave=true/false/"fieldname")
```
True is the default, and current behavior.
False is left to right, exhausting each stream.
A field name (with r.asc or r.desc) allows a merge-sort like merge step on a field, and demands that the streams are currently ordered.

**Comment by danielmewes** [comment]
Corresponding issue for the server: https://github.com/rethinkdb/rethinkdb/issues/5090#issuecomment-163110597

**Comment by nighelles** [comment]
Thanks.
