### ISSUE TITLE
State that you should start the RethinkDB server at the beginning of the ten-minute guide.

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#1024]
The [ten-minute guide](http://rethinkdb.com/docs/guide/javascript/) doesn't specify that you should start the RethinkDB server before connecting with a driver. It can simply copy the startup instructions from the quickstart.

It does state that you should "Read the quickstart" before beginning, but this may be too subtle to notice for readers.

**Comment by dineyw23** [comment]
Hi,
I am new to RethinkDB and recently started to explore it. I used the ten-minute guide and after I installed the client driver, I must say, I missed on starting the server before connecting with a driver(May be that's just me). I know a few other people just trying to explore RethinkDB who missed on starting the server. Just thought of sharing my experience,here, after seeing this issue.
