### ISSUE TITLE
Small parameter error on "Install RethinkDB on Windows" website

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1025]
Reported by @sceee in https://github.com/rethinkdb/rethinkdb/issues/5421 :

Thank you so much for providing the Windows Developer Preview.

I just wanted to point out that there is an error on the website
http://rethinkdb.com/docs/install/windows/

The command
`rethinkdb.exe -n jarvis --j cluster.example.com`
uses two "minus" chars before the cluster wheras the command would be correct the following way:
`rethinkdb.exe -n jarvis --j cluster.example.com`

**Comment by sceee** [comment]
Sorry for being so dump, the correct statement would be
`rethinkdb.exe -n jarvis -j cluster.example.com`
