### ISSUE TITLE
Fix broken links on docs/3-reql-practice/cookbook/index.md 

### ISSUE THREAD

**Issue by dineyw23** [rethinkdb/docs#1029]
I noticed the links to the three cookbooks for three official drivers on [index.html](https://github.com/rethinkdb/docs/blob/master/3-reql-practice/cookbook/index.md) are broken. I guess they should point [here](https://www.rethinkdb.com/docs/cookbook/)

**Comment by chipotle** [comment]
These links don't appear to actually be broken as deployed on the web site. Is there a way to reproduce the problem by clicking around on the site as built? (The URLs generated are taken from the `permalink:` field in the header, not the directory layout of the Markdown source.)

**Comment by dineyw23** [comment]
Hi,
I am new to RethinkDB and trying to explore and learn, I apologize for any inconvenience.
I noticed the `permalink: ` header states `docs/cookbook` and while browsing the deployed website it redirects to `docs/cookbook/javascript`. There is no way to reach `docs/cookbook` [here](https://www.rethinkdb.com/docs/cookbook/) other than editing the URL in the address bar?
So, I tried to edit the URL and may not have entered the right thing, my bad.
Unable to reproduce the produce, the issue is good be closed.

**Comment by chipotle** [comment]
No problem. And you're right, normally you can't reach `docs/cookbook/index.html` directly! The language switcher bar at the top of many documentation pages sets a cookie indicating the last language you've clicked, so pages that have multiple languages like the API documentation and the Cookbook will automatically show the page for the language you've been browsing. The default language is JavaScript, so if you haven't selected another language it's going to show you JavaScript.
