### ISSUE TITLE
r.http doc is missing nonAtomic

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1030]
http://rethinkdb.com/docs/external-api-access/

```js
r.table('stargazers').update(r.http(r.row('url')))
```

needs to be
```js
r.table('stargazers').update(r.http(r.row('url')), {nonAtomic: true})
```

**Comment by dineyw23** [comment]
Newbie here (*Apologies*), how does taking up this issue work? 
1. Reproduced it.
2. I understand why `{nonAtomic: true}` argument should be provided.
3. Should an explanation be added to the doc or just edit the update statement? 

Thanks.

**Comment by danielmewes** [comment]
Thanks for looking into this @dineyw23 .
I think just editing the update statement is enough, but adding a short explanation would be better (one sentence maximum, since it's not the focus of the article).

Note that we require a contributor license agreement before we can accept pull requests. You can read and sign it online at http://rethinkdb.com/community/cla/
