### ISSUE TITLE
New functionality in eachAsync.

### ISSUE THREAD

**Issue by nighelles** [rethinkdb/docs#1033]
https://github.com/rethinkdb/rethinkdb/issues/5056

I think I compiled the behavior in a comment near the bottom. As I understand it, the idea is to prefer this new syntax, and look towards making it the default in the future.

**Comment by danielmewes** [comment]
Another small change in 2.3: `eachAsync` no longer stops iterating if the user returns `false` from the callback.
It looks like we had never documented this detail in http://rethinkdb.com/api/javascript/each_async/ explicitly anyway, apart from saying "in an identical fashion to `each`".

We do currently mention this for `each` (http://rethinkdb.com/api/javascript/each/ : "when there are no more rows or when the callback returns `false`"), and this is still correct in 2.3.
