### ISSUE TITLE
i can't use delete()

### ISSUE THREAD

**Issue by hanxueming** [rethinkdb/docs#1036]
r.db('stf').table('tasks').get('abcd')('image').filter({pcgg: 'abcdefg'}).delete()

but it comment " e: Expected type SELECTION but found DATUM:"

**Comment by danielmewes** [comment]
This isn't really formulated as an issue for the documentation. Are you suggesting that we clarify when `delete()` can be used and when not?

Can you explain a bit what you're intending to do with this query?
What's the schema of the `tasks` table?

The `filter` in your query seems to apply to a nested array (`image`). `delete()` is to delete a whole document, not individual entries in an array. To delete certain elements in the array, you should use something like this:
```js
r.db('stf').table('tasks').get('abcd').update(function(doc) {
    return { image: doc('image').filter(function(element) {
        return element(pcgg).ne('abcdefg');
    })};
  })
```
(only the documents where `pcgg` is not equal to `abcdefg` will be left in the array after this)

https://github.com/rethinkdb/rethinkdb/issues/2692 is going to make operations like this easier.

**Comment by hanxueming** [comment]
@danielmewes , thanks, you solve my problem perfectly.
