### ISSUE TITLE
Asynchronous connections doc page says Tornado Deferred

### ISSUE THREAD

**Issue by MiracleB** [rethinkdb/docs#1039]
https://www.rethinkdb.com/docs/async-connections/

The page says and I quote: 

> After executing set_loop_type, r.connect will return a Tornado Deferred, as will r.run.

This is under the Twisted section, and therefore should be renamed to Twisted.

> After executing set_loop_type, r.connect will return a **Twisted** Deferred, as will r.run.

**Comment by danielmewes** [comment]
Thanks for opening an issue. Good catch.
