### ISSUE TITLE
Java Connection Thread Safety

### ISSUE THREAD

**Issue by bchavez** [rethinkdb/docs#1041]
From https://github.com/rethinkdb/rethinkdb/issues/5457#issuecomment-190574563

@vinaysshenoy 
> Actually, the RethinkDb driver [documentation](https://www.rethinkdb.com/docs/install-drivers/java/) (At the very end of the page) states that the connections are not thread-safe and recommends users to open a connection per thread or use a connection pool, so I wrote a pool like so.

I think connections are thread-safe now.

**Comment by danielmewes** [comment]
Thanks for opening an issue for this @bchavez .

**Comment by danielmewes** [comment]
@chipotle this changed just recently for the Java driver.
