### ISSUE TITLE
Issue for non-transitive connectivity and new functionality in server info

### ISSUE THREAD

**Issue by nighelles** [rethinkdb/docs#1042]
https://github.com/rethinkdb/rethinkdb/issues/4936

**Comment by nighelles** [comment]
Example:

`
{
"id":  "170e7194-7682-4e32-b9a4-e73f767d43b6" ,
"name":  "newton_ase" ,
"network": {
"canonical_addresses": [
...
] ,
"cluster_port": 29021 ,
"connected_to": {
"newton_2jv": true ,
"newton_j5r": true
} ,
...
}
`

**Comment by danielmewes** [comment]
That's an example from the `server_status` table right? (@chipotle the `connected_to` field is new)

How do servers whose names cannot be resolved show up in the `connected_to` list? Just with their UUID as the field name? We should probably document that case too.

Can you also post an example issue from `current_issues`?

**Comment by nighelles** [comment]
Example issue
```
{
"critical": false ,
"description": "There are currently servers that cannot see every server in the cluster. This may cause table availability issues." ,
"id":  "5ca75800-8f5a-58cf-947c-a5ed2545e96e" ,
"info": {
"message":  "Server connectivity is non-transitive." ,
"servers": [
"newton_ase" ,
"newton_j5r"
]
} ,
"type":  "non_transitive_error"
}
```
