### ISSUE TITLE
Add "awesome list" to a list of community resources

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#1045]
I'm not sure if we have an issue for maintaining a list of community resources -- but at this point, we have a lot of contributions, and it'd be useful to list the best ones.

One in particular would be @analytik's "awesome-rethinkdb" list that he's started here: https://github.com/analytik/awesome-rethinkdb

**Comment by danielmewes** [comment]
It probably makes sense to merge this with https://github.com/rethinkdb/docs/issues/1040

**Comment by danielmewes** [comment]
Closing in favor of https://github.com/rethinkdb/docs/issues/1040
