### ISSUE TITLE
Ordered optarg for eqJoin

### ISSUE THREAD

**Issue by nighelles** [rethinkdb/docs#1053]
The new faster eqJoin does not guarantee ordering of the elements anymore, so there's a new "ordered" optarg that maintains ordering if it's true, but it's slower.

https://github.com/rethinkdb/rethinkdb/issues/5115

**Comment by danielmewes** [comment]
I think this needs a bit of extra explanation:
`eqJoin` was never fully ordered in its result. However it used to guarantee that its output was ordered based on the (left) input stream.

For example:
```js
r.expr([{foreignKey: 1}, {foreignKey: 2}].eqJoin("foreignKey", r.table("other"))
```
was guarantees to first emit joined documents from `other` that matched `{foreignKey: 1}`, followed by all documents from `other` that matched the key `{foreignKey: 2}`.
If the join had been on a secondary index, and there were multiple matches for e.g. key `1`, the order of those matches compared to each other was never guaranteed. However you would never see a match for key `2` before seeing all matches for key `1`.

In 2.3, this no longer holds, and results can be in any order whatsoever. The new optarg `{ordered: true|false}` restores the old behavior when set to `true`. By default it is `false`.

**Comment by danielmewes** [comment]
The disadvantage of setting `ordered` to `true` is that it's slower (sometimes by a lot).
