### ISSUE TITLE
Document new --bind parameters

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1055]
The new 2.3 parameters listed in https://github.com/rethinkdb/rethinkdb/issues/5467 need to be added to http://www.rethinkdb.com/docs/cli-options/ .

I believe the behavior that Marc described there was implemented for the case where there's both a general `--bind` and a more specific `--bind-*` option (@nighelles correct?).

**Comment by danielmewes** [comment]
We should also change http://www.rethinkdb.com/docs/security/ accordingly.
The section "Securing the intracluster port" and the top paragraph of "Securing the web interface" can now be simplified to use `--bind-http localhost` and `--bind-cluster localhost` respectively.

**Comment by nighelles** [comment]
Yes, that's the correct conflict behavior.
