### ISSUE TITLE
Document TLS encryption in RethinkDB 2.3

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1057]
RethinkDB 2.3 is going to add optional SSL/TLS encryption for all connections, intra-cluster connections, client connections and for the HTTP interface.

The corresponding issue is https://github.com/rethinkdb/rethinkdb/pull/5381/

The following two pages (at least) need updating:
* http://www.rethinkdb.com/docs/security/ should have a description of how to set up a TLS-secured cluster
* http://www.rethinkdb.com/docs/cli-options/

Assigning to myself to write up a summary of how this works. Going to pass it on to @chipotle later.

**Comment by danielmewes** [comment]
The command line arguments have minimally changed from those described in the issue. This is the actual list from `next`:
```
TLS options:
  --web-tls                                   secure the web administration console
                                              with TLS
  --web-tls-key key_filename                  private key to use for web
                                              administration console TLS
  --web-tls-cert cert_filename                certificate to use for web
                                              administration console TLS
  --driver-tls                                secure client driver connections with
                                              TLS
  --driver-tls-key key_filename               private key to use for client driver
                                              connection TLS
  --driver-tls-cert cert_filename             certificate to use for client driver
                                              connection TLS
  --driver-tls-ca ca_filename                 CA certificate bundle used to verify
                                              client certificates; TLS client
                                              authentication disabled if omitted
  --cluster-tls                               secure intra-cluster connections with
                                              TLS
  --cluster-tls-key key_filename              private key to use for intra-cluster
                                              connection TLS
  --cluster-tls-cert cert_filename            certificate to use for intra-cluster
                                              connection TLS
  --cluster-tls-ca ca_filename                CA certificate bundle used to verify
                                              cluster peer certificates
  --tls-ciphers cipher_list                   specify a list of TLS ciphers to use;
                                              default is 'EECDH+AESGCM'
  --tls-ecdh-curve curve_name                 specify a named elliptic curve to use
                                              for ECDHE; default is 'prime256v1'
  --tls-dhparams dhparams_filename            provide parameters for DHE key
                                              agreement; REQUIRED if using DHE
                                              cipher suites; at least 2048-bit
                                              recommended
```

**Comment by danielmewes** [comment]
https://hub.docker.com/r/jlhawn/rethinkdb-tls/ has a good introduction on how to set things up.

--
Usually the first step is to generate a private key and matching certificate. This can be done with the OpenSSL command line tool, among others:
```
openssl genrsa -out key.pem 2048
openssl req -new -x509 -key key.pem -out cert.pem -days 3650
```

The second command will ask a few questions to identify the server. Most values can be ignored for testing purposes, but the "Common name" must match the hostname under which the server will be reachable for some clients to be able to connect (e.g. Python 3.5 appears to verify this). For local testing, we can specify it as "localhost".

--
The easiest one is configuring the web UI for TLS:
```
rethinkdb --web-tls --web-tls-key key.pem --web-tls-cert cert.pem
```
With this set, the web UI needs to be accessed via `https://localhost:8080` (or whatever host+port is used). It will encrypt the connection, but it will *not* provide any additional security. In particular, anyone who can reach the server on an interface that is enabled via a `--bind` option can still access the web UI.

--
The next one is client (driver) encryption, which can be enabled like this:
```
rethinkdb --driver-tls --driver-tls-key key.pem --driver-tls-cert cert.pem
```

This enables encrypted driver connections. Usually the clients will need the certificate (cert.pem) that we use to verify the server's identity. For example in Python:
```py
import rethinkdb as r
r.connect(host="localhost", port=28038, ssl={"ca_certs": "cert.pem"})
```

As an additional step, client-side certificate authentication can be enabled:
```
rethinkdb --driver-tls --driver-tls-key key.pem --driver-tls-cert cert.pem --driver-tls-ca cert.pem
```
This will make the server only accept clients that provide a certificate that was signed with `cert.pem` (or that is `cert.pem` itself). This can be used to secure the client port against unauthorized access. Currently our official clients don't support client-side certificates, or at least we don't have it documented and I'm not sure how to enable that option.

--
Finally, the intra-cluster communication can be encrypted:
```
rethinkdb --cluster-tls --cluster-tls-key key.pem --cluster-tls-cert cert.pem --cluster-tls-ca cert.pem
```

Note that in this case, we always require the `--cluster-tls-ca` option. In this example, we're using our certificate as the CA certificate as well. We could also use a different CA certificate, and sign our `cert.pem` with that certificate. Other servers can only connect if they have a certificate signed by the provided CA certificate.

**Comment by danielmewes** [comment]
I think I'm going to remove the `--http-tls`, `--driver-tls` and `--cluster-tls` options. Instead we will enable them implicitly if any of the `--http-tls-*`, `--driver-tls-*` or `--cluster-tls-*` options is provided.

**Comment by danielmewes** [comment]
@chipotle Please let me know which other details you need on this.

**Comment by danielmewes** [comment]
@chipotle My fixes for https://github.com/rethinkdb/rethinkdb/issues/5554 which are currently in code review change the server arguments as follows:

```
TLS options:
  --http-tls-key key_filename                 private key to use for web
                                              administration console TLS
  --http-tls-cert cert_filename               certificate to use for web
                                              administration console TLS
  --driver-tls-key key_filename               private key to use for client driver
                                              connection TLS
  --driver-tls-cert cert_filename             certificate to use for client driver
                                              connection TLS
  --driver-tls-ca ca_filename                 CA certificate bundle used to verify
                                              client certificates; TLS client
                                              authentication disabled if omitted
  --cluster-tls-key key_filename              private key to use for intra-cluster
                                              connection TLS
  --cluster-tls-cert cert_filename            certificate to use for intra-cluster
                                              connection TLS
  --cluster-tls-ca ca_filename                CA certificate bundle used to verify
                                              cluster peer certificates
  --tls-ciphers cipher_list                   specify a list of TLS ciphers to use;
                                              default is 'EECDH+AESGCM'
  --tls-ecdh-curve curve_name                 specify a named elliptic curve to use
                                              for ECDHE; default is 'prime256v1'
  --tls-dhparams dhparams_filename            provide parameters for DHE key
                                              agreement; REQUIRED if using DHE
                                              cipher suites; at least 2048-bit
                                              recommended
```

This makes enabling TLS implicit (once the `*-tls-key` and `*-tls-cert` arguments are provided, it's automatically enabled). I also renamed `--web-tls-*` arguments to `--http-tls-*` arguments for consistency with other server options (I don't remember if I originally recommended the `web` one in the pull request, but on second look I found that we use `http` almost everywhere else at the moment).

I'm going to update my examples above.

**Comment by danielmewes** [comment]
(Also mentioning @jlhawn to note the command line argument changes)

**Comment by chipotle** [comment]
Just to verify, are all these available as configuration file options as well? (And are all the new bind commands available in the config file?)

**Comment by danielmewes** [comment]
@chipotle Yes to both.

**Comment by scottder** [comment]
How will rethink instances in proxy mode work, or will they just need the intracluster options enabled?

**Comment by danielmewes** [comment]
@scottder Yes, you have to use the same intracluster options as for the main servers.

**Comment by marcverkerk** [comment]
Hi folks at RethinkDB,
I tried to start a proxy. Works fine if I do not use TLS. 

When using TLS (the servers in the cluster started with --cluster-tls-* arguments) i am not able to specify --cluster-tls-* arguments on the proxy. It seems these arguments are not being recognized when starting in proxy node.

For completeness here my systemd service:
[Unit]
Description=RethinkDB as a proxy
After=NetworkManager-wait-online.service network.target network-online.target
Wants=NetworkManager-wait-online.service network-online.target

[Service]
Type=simple
PIDFile=/var/run/rethinkdb.pid
User=rethinkdb
Group=rethinkdb
PermissionsStartOnly=true
ExecStartPre=/bin/mkdir -p /var/log/rethinkdb
ExecStartPre=/bin/chown rethinkdb:rethinkdb /var/log/rethinkdb
Restart=on-failure

#this line works when cluster is not using TLS
ExecStart=/usr/bin/rethinkdb proxy --join 192.168.0.3:29015 --bind-cluster all --initial-password auto  --log-file /var/log/rethinkdb/rethinkdb.log

#this line is not working
#ExecStart=/usr/bin/rethinkdb proxy --join 192.168.0.3:29015 --bind-cluster all --initial-password auto --cluster-tls-key=/etc/ssl/private/tlmd.key.pem --cluster-tls-cert=/etc/ssl/certs/tlmd.cert.pem --cluster-tls-ca=/etc/ssl/certs/mapp-ca.pem --log-file /var/log/rethinkdb/rethinkdb.log

[Install]
WantedBy=multi-user.target
