### ISSUE TITLE
tableCreate API doc has confusing working about compound primary keys

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1060]
This caused some confusion over here: https://github.com/rethinkdb/rethinkdb/issues/3875#issuecomment-199586101

https://www.rethinkdb.com/api/javascript/table_create/ says:
> Using an array as a primary key creates a compound index; read the documentation on compound secondary indexes for more information, as it applies to primary keys as well.

I think we usually use the term "compound index" to refer to an index that covers multiple fields. However in the case of a primary index, we still only use a single field, even if that field contains array values.

I suggest:
"Using an array in the primary key field makes the primary index behave similarly to a compound secondary index; read the documentation on compound secondary indexes for more information, as it applies to primary keys as well. Note that the primary index still can only cover a single field, while compound secondary indexes can cover multiple fields in a single index."

**Comment by brandonbloom** [comment]
Typo in issue title: s/working/wording/
