### ISSUE TITLE
Changefeed types

### ISSUE THREAD

**Issue by nighelles** [rethinkdb/docs#1065]
https://github.com/rethinkdb/rethinkdb/issues/5188

**Comment by danielmewes** [comment]
Quick explanation copied from #1068:

rethinkdb/rethinkdb#5188 introduced a new `include_types` boolean optarg for the `changes` command.

If turned on, every result on a changefeed will have a `type` field with one of the following values:
"add", "remove", "change", "initial", "uninitial", "state"
