### ISSUE TITLE
Issue with sidebar

### ISSUE THREAD

**Issue by AmeyDeshpande** [rethinkdb/docs#1069]
When we clink on 'System tables' on a side bar, all the menus in a side-bar collapse.
issue https://rethinkdb.com/docs/backup/. In this link we can see side bar with all sub-menu in 'Administration'. When we click on 'System tables', all menus will collapse.

**Comment by rchordiya** [comment]
The solution is:
Open index.html present at location /docs/_site/docs/system-tables. And make the following changes:
line number: 231 & 662   
Replace <ul>  with  <ul class="expanded"> and               
replace <li class=""> with <li class="active"> on line number 234 & 665
