### ISSUE TITLE
RethinkDB.com - Typo in code on Javascript cookbook page ?

### ISSUE THREAD

**Issue by jouerose** [rethinkdb/docs#1080]
Hello,

on this page: https://rethinkdb.com/docs/cookbook/javascript/
Under this title: Filtering based on the presence of a value in an array
We have the following sentence: "Suppose we have a table users with documents of the following form"
which has "users" in plural form yet in the four other occurrences of the table "user" it is in singular form.
Is there a particular reason for this difference? thank you for your time.

**Comment by chipotle** [comment]
I think it's just a case of different examples being written by different authors at different times. At some point we'll try to go through all the docs to check for inconsistencies like this -- but there's no functional difference between calling a table `user` or `users`.
