### ISSUE TITLE
Javascript Quickstart code does not match Data Explorer API

### ISSUE THREAD

**Issue by jouerose** [rethinkdb/docs#1088]
in the javascript quickstart guide here http://rethinkdb.com/api/javascript/
is referred several times r.table but in the data explorer you can get the table only after doing r.db as in 
`r.db('test').table('tv_shows')` and not `r.table('tv_shows')`.
I am using RethinkDB 2.3 Fantasia. 

thanks

**Comment by jouerose** [comment]
Actually it does work but it is the suggested completion that does not have `.table` as a method

**Comment by danielmewes** [comment]
Thanks for opening an issue @jouerose . I think the current intro code is ok.

We'll likely add `r.table` auto-completion to the Data Explorer once we make the default DB configurable there (compare the discussion in https://github.com/rethinkdb/rethinkdb/issues/829 ).
