### ISSUE TITLE
javascript docs error:  talks about coerce_to instead of coerceTo

### ISSUE THREAD

**Issue by mike-thompson-day8** [rethinkdb/docs#1092]
The page https://www.rethinkdb.com/api/javascript/object/  contains this code:
```
r.expr([[A, B], [C, D]]).coerce_to('OBJECT')
```
But that uses the python name `coerce_to`  instead of using the correct javascript name of  `coerceTo`

**Comment by danielmewes** [comment]
Thanks for the bug report. Pinging @chipotle .

**Comment by chipotle** [comment]
This was fixed in c2f68e8ae9040f2349421af04981196bba4f66a9 by @rchordiya
