### ISSUE TITLE
Unclear how to upsert array entries

### ISSUE THREAD

**Issue by cefn** [rethinkdb/docs#1098]
I have insert logic like this, which fails if there's no memberships field, which I don't know how to fix to be more like an upsert behaviour (creating the field 'memberships' as an array before appending).

Currently it's responding with...

'No attribute `memberships`...'

```
return r.table("users").get(userId).update({
                memberships:r.row("memberships").append({
                    groupId:groupId,
                }),
            })
```

Is the only way to resolve a missing referenced array to do explicit checking and insertion of the array field?

I would consider using insert with the known primary key, but it's not clear how merge is handled when a merged field entry is an array (index-by-index overwriting, as if the numbered indexes were field names? alternatively, are two arrays merged by appending? it would be good to state this somewhere).

From the update documentation, I understand the above is the canonical way to introduce an entry to an existing array. Ideally there would be documented examples for typical array (nested field) operations, such as this - lazy-creating an array, and inserting a member, as it's potentially a very common use case in a schemaless data structure.

**Comment by cefn** [comment]
Here's a functional example which uses r.branch explicitly to handle the two cases of insert or upsert...

```javascript
    promiseAddUserToGroup:function(userId, groupId){
        return this.registry.dbConnectionPromise.then(function(dbConnection){
            var membership = {groupId:groupId};
            return r.table("users").get(userId).update(
                    r.branch(
                        r.row.hasFields("memberships"),
                        {memberships:r.row("memberships").append(membership)},
                        {memberships:[membership]}
                    )
                )
                .run(dbConnection)
        })
    }
```

Is there a less fiddly way to do it?

**Comment by chipotle** [comment]
The `update` page goes into some detail on how to update nested fields, and the use case you're talking about is the one that has the example of adding another note to Bob Smith's record--except that that example doesn't show what happens if the `notes` field doesn't exist, which is the error that you hit. So I think we should update that example.

But, actually, there _is_ a less fiddly way to do this: the [default](http://rethinkdb.com/api/javascript/default/) command. For your example, I think what you'd want would be something like:

```js
promiseAddUserToGroup: function (userId, groupId) {
  return this.registry.dbConnectionPromise.then(function (dbConnection) {
    var membership = {groupId: groupId};
    return r.table('users').get(userId).update(
      {memberships: r.row('memberships').default([]).append(membership)}
    );
  });
}
```
