### ISSUE TITLE
Alternative to run(conn)

### ISSUE THREAD

**Issue by cefn** [rethinkdb/docs#1104]
Forgetting run(conn) at the end of a query chain before passing back a promise is my most common error so far. Isn't it possible to use a function callback structure a bit like a promise to ensure queries are run correctly?

A function which returns anything which doesn't evaluate to a query can be routed to validation code and throw an immediate error, rather than waiting for the error to hit application code in the form of an unterminated query.

Better still, all queries are actually evaluated by calling ```run(conn)``` since this is an automatic by-product of returning from the function.

Pseudo-code might look like...

```javascript
conn = r.connect({
    db: 'marvel'
})

var tableResultPromise = conn.promiseResult(function(db){
  return db.table('marvel')
});

var cursorResultPromise = conn.promiseResult(function(db){
  return db.table('dc').getAll('superman', 'ant man')
});

//this use of toArray is a promise-oriented extension to the API
var itemsResultPromise = conn.promiseResult(function(db){
  return db.table('dc').getAll('superman', 'ant man').toArray()
});

itemsRecordsPromise.then(function(result){
    console.log(JSON.stringify(result, null, '\t'))
})
```

**Comment by danielmewes** [comment]
@cefn Since this is a proposal for a driver API change and not a documentation issue, I'm going to move this to our main issue tracker over here: https://github.com/rethinkdb/rethinkdb/issues/

**Comment by danielmewes** [comment]
@cefn See https://github.com/rethinkdb/rethinkdb/issues/5732 , I'm going to comment there.
