### ISSUE TITLE
Document client_port/client_address on connection object

### ISSUE THREAD

**Issue by nighelles** [rethinkdb/docs#1127]
For https://github.com/rethinkdb/rethinkdb/issues/5571

nighelles/5571

**Comment by danielmewes** [comment]
I think we actually haven't documented these for any of the drivers yet.

**Comment by chipotle** [comment]
I've looked through related tickets, but I admit I can't figure out just where the client port and address are exposed by these changes. Is this something in the return values from `r.connect`?

**Comment by danielmewes** [comment]
This is the syntax in the various drivers, where `conn` is a connection object in each case. In all cases except Java, the `clientPort` is an integer and `clientAddress` is a string.

JavaScript
```js
// Note: These are properties of the connection, not methods
conn.clientPort
conn.clientAddress
```

Python
```py
conn.client_port()
conn.client_address()
```

Ruby
```ruby
# These are methods, you can optionally use `()`
conn.client_port
conn.client_address
```

Java
```java
conn.clientPort() // Returns Optional<Integer>
conn.clientAddress() // Returns Optional<SocketAddress>
```

The client port is the outgoing TCP port that the connection uses on the client-side. It is randomly assigned by the operating system, and can be used to match client entries in the `r.db('rethinkdb').table('jobs')` table to a client process.

**Comment by danielmewes** [comment]
@chipotle are these still undocumented?

**Comment by chipotle** [comment]
They are. I think the way this ticket was written initially confused me—this isn't something that needs to be added to driver documentation, it needs to be added to the `connect` API documentation.
