### ISSUE TITLE
rethinkdb erroring out on count of index

### ISSUE THREAD

**Issue by monkeyboy64** [rethinkdb/docs#1129]
I am trying to do this query: r.db("numetric").table("prostar__2cef1ff5_9a7e_4ddf_a405_04a2d0a26757").getAll(true, {index: "indexed"}).count()

on a table with ~13M records. There are only two values in the index, true or false.  Currently all the records have the value true so.

The query errors out with an unknown error.

There are three servers with 8 GB cache allocated to each. There are 3 shards/3 replicas on the table.

The records look like this:

{
    "ActualWeight": 6 ,
    "Amount": 0.65 ,
    "BatchId": null ,
    "CalculatedAmount": 0.51 ,
    "CarrierDescription":  "28" ,
    "CarrierOrderNumber":  "26" ,
    "CarrierType":  "25" ,
    "Category":  "14" ,
    "ClientName":  "2" ,
    "ClientOrderNumber":  "42" ,
    "Cost": 0.51 ,
    "CreatedDate":  "2015-01-05T14:50:46.967" ,
    "Description":  "16" ,
    "DetailName":  "38" ,
    "DetailValue":  "39" ,
    "DueDate":  "2015-01-05T14:50:46" ,
    "EndDate":  "2015-01-03T23:55:55" ,
    "InvoiceId": 314 ,
    "InvoiceLineCarrierId": 1453456 ,
    "InvoiceLineDetailId": null ,
    "InvoiceLineId": 2219085 ,
    "InvoiceNumetricId": 20 ,
    "InvoiceOrderId": 484423 ,
    "InvoiceStatus":  "3" ,
    "IsIntercept": null ,
    "IsPassThrough": false ,
    "IsReplacement": false ,
    "IssuedDate":  "2015-01-05T14:50:46.967" ,
    "LocationId": 1 ,
    "OrderClientName":  "40" ,
    "OrderNumber":  "22" ,
    "OrderOrderNumber":  "41" ,
    "OrderShipDate":  "2014-11-17T00:00:00" ,
    "OrderTrackingNumbers":  "44" ,
    "ProcessPeriod":  "11" ,
    "QBInvoiceRef":  "9" ,
    "Quantity": 1 ,
    "ShipDate":  "2014-12-22T00:00:00" ,
    "ShipToCountry":  "35" ,
    "ShipToPostalCode":  "36" ,
    "ShippingMethod":  "29" ,
    "StartDate":  "2014-12-28T00:00:00" ,
    "SubCategory":  "15" ,
    "TrackingNumber":  "30" ,
    "Weight": 6 ,
    "WorkOrderId": null ,
    "Zone":  "32" ,
    "__metadata": {
    "indexed": true ,
    "updated": "2015-01-05T14:50:46.967"
}

**Comment by danielmewes** [comment]
Hi @monkeyboy64 . This is the issue tracker for the RethinkDB documentation. I've copied your issue to https://github.com/rethinkdb/rethinkdb/issues/5794 and am going to reply there.
