### ISSUE TITLE
Note important difference between `r.args` and `apply`

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1136]
The JavaScript version of the `r.args` documentation currently says http://rethinkdb.com/api/javascript/args/ :

> This is analogous to using apply in JavaScript.

The other language versions have similar statements.

However it turns out that `r.args` has one subtle but sometimes important difference to those native commands.

Using `r.args` with a command that evaluates its arguments lazily can yield different results. Since `r.args` takes an array, all of the arguments will be eagerly evaluated before being passed into the parent term.

For example
`r.and(a, b)` is *not* equivalent to `r.and(r.args([a, b]))` if `b` has any side effects.
A simple example is `r.and(false, r.error("test"))` vs. `r.and(r.args([false, r.error("test")]))`. The former evaluates to `false`, while the latter throws an error.

We should clearly describe this difference in the `r.args` documentation.

(background: A user ran into this https://github.com/rethinkdb/rethinkdb/issues/5821)

**Comment by mlucy** [comment]
@danielmewes -- I don't think any language preserves laziness through splicing, does it?  What's the equivalent JS `and` that behaves differently?

**Comment by danielmewes** [comment]
Well, in many languages function arguments are never lazy, so there's nothing to preserve.

The important point though is that using `apply` in your ReQL query in JavaScript is not equivalent to using `r.args` in your ReQL query in JavaScript. The former operates on AST objects, and thereby maintains lazyness within the resulting ReQL query, while the latter operates on ReQL values and discards lazyness.
You're right that it's "analogous", but it's not equivalent.

**Comment by mlucy** [comment]
@danielmewes -- Ah!  I misunderstood, you're right that it's confusing.  (I thought you were comparing `r.args` in ReQL to `apply` in pure JS, not to using `apply` in JS to build ReQL terms.)
