### ISSUE TITLE
Add thinkagain ORM to integrations list

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1138]
@mbroadst forked Thinky and modified it to use json-schema specifications. His fork is available at https://github.com/mbroadst/thinkagain under the name thinkagain.

We should add it to the ORM list at http://rethinkdb.com/docs/frameworks-and-libraries/

> The module is essentially a drop-in replacement for thinky, of course using json-schema instead of thinky's schema. This means:
> ```
> let Model = thinky.createModel('person', {
>   id: String,
>   str: String,
>   num: Number
> })
> ```
> 
> becomes:
> ```
> let Model = thinkagain.createModel('person', {
>   type: 'object',
>   properties: {
>     id: { type: 'string' },
>     str: { type: 'string' },
>     num: { type: 'number' }
>   }
> });
> ```
> 
> There are also a few notable changes:
>   - virtual fields are not implemented
>   - validation is always asynchronous (i.e. Model.validate(), Document.validate() return promises)
>   - all validation-specific options (`enforce_type`, `enforce_missing`, etc) have been removed, in favor of ajv's internal options.
>   - Oh, also no documentation whatsoever presently (though for the most part thinky's documentation still holds true) :) This will obviously change in the future, pending interest in the project.

**Comment by mbroadst** [comment]
👍
