### ISSUE TITLE
Typo on ruby insert page

### ISSUE THREAD

**Issue by hubsmoke** [rethinkdb/docs#1139]
https://rethinkdb.com/api/ruby/insert/

All the way at the bottom there's

`# assume new_memos is a list of memo documents to insert
r.table("memos").insert(new_memos, :conflict => lambda { |id, old_doc, new+doc|
    new_doc.merge({:content => old_doc['content'] + "\n" + new_doc['content']})
}).run(conn)`

The parameter `new+doc` should be `new_doc`

**Comment by danielmewes** [comment]
Good catch!

Pinging @chipotle
