### ISSUE TITLE
Installing RethinkDB as Windows service

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1146]
We just merged support for running RethinkDB as a Windows service (https://github.com/rethinkdb/rethinkdb/issues/5810).

We should explain this in https://rethinkdb.com/docs/start-on-startup/ and maybe mention it on the Windows install page as well.

The process for setting up RethinkDB as a service is as follows:

1. Create a configuration file for the RethinkDB server. A template can be downloaded from https://github.com/rethinkdb/rethinkdb/blob/next/packaging/assets/config/default.conf.sample . At least the `directory` line should be specified. All other settings are optional. If `directory` is not specified, RethinkDB will put its data in `c:\Windows\System32\rethinkdb_data`, which is probably not what users want. To test a configuration file before using it as a service, you can run `rethinkdb.exe --config-file <path to config file>` manually.
2. Open a command line, go to the location of the `rethinkdb.exe` executable, and run:
  ```
rethinkdb.exe install-service --config-file <path to config file>
```
3. RethinkDB will install a service under the name `rethinkdb_default` and start it. You can use Windows' service manager to Monitor the status of the RethinkDB service, or to stop and/or restart it later. By default, the RethinkDB service will automatically start when the system starts.

Some relevant notes:

* The service created by `rethinkdb.exe install-service` relies on `rethinkdb.exe` and on the config files to remain in the locations where they were when `rethinkdb.exe install-service` were called. If one of these files gets moved, the service must be re-installed (run `rethinkdb.exe remove-service` first).
* Changes in the configuration file after the initial install will take effect when the service is restarted.
* By default, the service is installed to run with System user privileges. For improved security, the service can be installed with a different user account. This can be done as follows:
  ```
rethinkdb.exe install-service --config-file <path to config file> --runuser <domain>\<user name> --runuser-password <password of the user>
```
(the `<domain>` is the Windows domain in which the user can be found. For a local user, this is the name of the server itself. If the user is from an Active Directory or Windows Domain, it must be the name of the directory)

To remove a service:
```
rethinkdb.exe remove-service
```

Both `install-service` and `remove-service` also accept the `--instance-name <name>` option. This can be used if you want to run multiple instances of RethinkDB on the same server. Each instance will get its own entry in the Windows Service manager, and can be configured and started/stopped separately.

**Comment by danielmewes** [comment]
Screenshot of what the service looks like in Windows' service manager after being installed by `rethinkdb.exe install-service`:
![rethinkdb service](https://cloud.githubusercontent.com/assets/505365/16326426/5894d262-397b-11e6-9176-8a865ddc50d5.PNG)

**Comment by JollyBrackets** [comment]
Hi @danielmewes 

When I try to run **rethinkdb.exe install-service** I get following error:
**ERROR: Unrecognized subcommand 'install-service'. Try 'rethinkdb help'.**

Is this not supported in version 2.3.5-windows (MSC 190023506) ?

**Comment by danielmewes** [comment]
@JollyBrackets Is is not unfortunately. This feature will only be supported in the next RethinkDB release (2.4).

**Comment by JollyBrackets** [comment]
@danielmewes, ok thanks, looking forward to the release then! Is there another way to achieve this until then?

**Comment by suddenelfilio** [comment]
+1

**Comment by tachikaw** [comment]
Hi, I can not start the RethinkDB as Windows service (returning 1053 timeout error), how could I do this, or is not possible (or maybe wait for the 2.4.0 version)?

**Comment by toshendradalvi** [comment]
When is the rethink Db 2.4.0 version is going to release?

**Comment by chipotle** [comment]
While your interest is awesome, appending questions to a long-closed documentation issue is probably not the best way to get solid answers. :)

For information about open-rethinkdb timelines and projects, I'd suggest keeping up with the community Slack:

http://slack.rethinkdb.com

Also, there's a Google Docs file which talks about planning meetings:

https://docs.google.com/document/d/1cTqKt1_EBanGoVmYyahdLyDD8dhCa0SdD0CbjbP67f8/preview

**Comment by YannisMarios** [comment]
This is still not working v2.3.6

C:\rethinkdb-2.3.6>rethinkdb.exe install-service --config-file default.config
ERROR: Unrecognized subcommand 'install-service'. Try 'rethinkdb help'.

<img width="725" alt="screenshot_1" src="https://user-images.githubusercontent.com/11289298/30278756-ff4415fe-9713-11e7-8fe1-3003da9a75d6.png">
