### ISSUE TITLE
Global `r.union` variant not listed in API docs

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1147]
This came up here https://github.com/rethinkdb/rethinkdb/issues/5872#issuecomment-228214307

**Comment by marshall007** [comment]
I would imagine all the ones added in rethinkdb/rethinkdb#4846 were never documented either:

- `group`
- `reduce`
- `count`
- `sum`
- `avg`
- `min`
- `max`
- `distinct`
- `contains`
