### ISSUE TITLE
Changefeed documentation: includeStates mentioned instead of includeTypes

### ISSUE THREAD

**Issue by larkost** [rethinkdb/docs#1151]
Our user @rdunnington found and reported this over in our [main repository](rethinkdb/rethinkdb#5907).

In the Including result types subsection on the Changefeeds in RethinkDB page, the documentation mentions:
> The includeStates optional argument adds a third field, type, to each result sent. The string values for type are largely self-explanatory:

I believe it should read:
> The includeTypes optional argument adds a third field, type, to each result sent. The string values for type are largely self-explanatory:

Looks like it has the same problem for all languages (javascript, python, ruby, and Java).

https://rethinkdb.com/docs/changefeeds/javascript/

**Comment by jeffzimmerlin** [comment]
Ran into the same issue today, and came to the same conclusion.
