### ISSUE TITLE
Fix upsert in FAQ

### ISSUE THREAD

**Issue by VeXocide** [rethinkdb/docs#1156]
In the FAQ we still reference the old `{"upsert": true}` in a question about upserts, this should be updated to use `conflict` optional argument.

**Comment by chipotle** [comment]
There's nothing about upserts in the FAQ. As with #1155, this appears to be referencing the November 2012 blog post "Answers to common questions about RethinkDB," which begins with a big italic warning block talking about how it's very out of date, and specifically mentions that the `insert` command now uses a different syntax for upserts.
