### ISSUE TITLE
Missing colon in Tornado example

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1157]
Reported by @arnau in https://github.com/rethinkdb/rethinkdb/issues/5939 : 

--

Hi, this is a small Python syntax issue in https://rethinkdb.com/blog/async-drivers/

In the example

```python
import rethinkdb as r
from tornado import ioloop, gen

r.set_loop_type("tornado")

@gen.coroutine
def print_changes():
    conn = yield r.connect(host="localhost", port=28015)
    feed = yield r.table("table").changes().run(conn)
    while (yield feed.fetch_next())
        change = yield feed.next()
        print(change)

ioloop.IOLoop.current().add_callback(print_changes)
```

I would have expected line 10 (`while (yield feed.fetch_next())`) to end with a colon (`:`).

**Comment by chipotle** [comment]
This is not actually in the documentation, but in a blog post about the asynchronous driver support when it was introduced. I'll fix the typo there.

**Comment by chipotle** [comment]
Fixed in https://github.com/rethinkdb/www/commit/f79cd574044ffef7e5b1373fe82e04542c18ea62
