### ISSUE TITLE
`r.connect` and `conn.run` in Ruby need documentation for block-style usage

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/docs#116]

**Comment by mlucy** [comment]
This would still be good to do.  @chipotle, do you know if this ever made it on to the site?

**Comment by chipotle** [comment]
I'm pretty sure it hasn't. I can pick it up.

**Comment by chipotle** [comment]
When you use this style with `run`, how does it work? Something like this, where you're just able to leave off the `.run(conn)` at the end of a given query? 

```rb
conn.run(:noreply => true) {
    r.table('marvel').insert([ a, b, c, .. ])
    r.table('dc').insert([ x, y, z, ... ])
}
```

**Comment by mlucy** [comment]
@chipotle -- it looks like this:
```rb
r.connect(host: 'newton) {|conn|
  r.table('test').insert(...).run(conn)
} # `conn` is closed when the block exits.
```

**Comment by chipotle** [comment]
I have that one covered, but the description  of "`r.connect` and `conn.run` need documentation for block style usage" made me assume you could pass a block to both `connect` and `run`.

**Comment by mlucy** [comment]
Ah, that looks like:
```
r.table('test').run(conn) {|cursor|
  cursor.each{...}
} # `cursor` is closed when the block exits
```
