### ISSUE TITLE
Explain meaning of `author_full_name` field in Secondary index documentation

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1164]
In the `eqJoin` example of the compound index section of http://www.rethinkdb.com/docs/secondary-indexes/javascript/#compound-indexes we use a field called "author_full_name" in the "posts" table.

For someone who isn't familiar with how `eqJoin` works, it might not be clear that "author_full_name" is just the name of a field. A user on Slack assumed that it was the name of a second compound index for example, and was wondering what that index was containing.

We should explain above the example that the documents in the `posts` table have a field called `author_full_name` and that we assume that it contains the names of the posts' authors in the form `[last_name, first_name]`.

**Comment by nicholastulach** [comment]
Or provide sample data in the example that reflect the data used (e.g. `posts.author_full_name`).
