### ISSUE TITLE
Suggestion for troubleshooting FAQ: Explain swappiness on Linux

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1166]
Lately we've got many questions from users who are seeing the "RethinkDB is using swap" warning, even though they have plenty of RAM available (e.g. https://github.com/rethinkdb/rethinkdb/issues/5865#issuecomment-236632154).

I've looked into some of those cases, and they were due to the default setting of the `swappiness` Linux kernel parameter.

This answer on Askubuntu explains very well what the parameter means and how to change it: http://askubuntu.com/a/103916/209792

I think we should add an entry to http://rethinkdb.com/docs/troubleshooting/ that explains:

1. What `swappiness` is (briefly)
2. How to check the current value of `swappiness` (`cat /proc/sys/vm/swappiness`)
3. How to change the value (adding the line `vm.swappiness = 10` to `/etc/sysctl.conf`, then reboot)
4. That we recommend a swappiness value of 10 for running RethinkDB.

@chipotle

**Comment by chipotle** [comment]
Is the "RethinkDB is using swap" warning the message mentioned under [Memory availability issues](https://www.rethinkdb.com/docs/system-issues/#memory-availability-issues) in the System issues documentation? If so, this should probably go here, too.

**Comment by danielmewes** [comment]
@chipotle Yes, that's the one. Good catch.
