### ISSUE TITLE
Drivers page shows official JS driver as "JavaScript", inofficial (rethinkdbdash) as "Node.js"

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1171]
https://rethinkdb.com/docs/install-drivers/ currently lists our official JS driver as "JavaScript". At the same time it lists the inofficial rethinkdbdash driver as "Node.js".

This confused at least one user, who thought that we didn't have an official node.js driver.

In reality, both drivers are for Node.js. We should probably list our own driver as `Node.js` as well.

**Comment by chipotle** [comment]
I think we probably need to list both as JS, if the inconsistency is a problem, and just note that JS drivers require Node. We use "JavaScript" for the name of our official driver absolutely everywhere else. Not only would changing that be difficult, it would be inconsistent—we refer to the language everywhere else, not the framework. Does our official JS driver require Node? (Is there any other server-side JS environment?)

**Comment by danielmewes** [comment]
It does require node, and we also list that on the install page that you get to when clicking on the driver in the list.
You're right that we do refer to it as "JavaScript" everywhere else, so listing both of them as "JavaScript" seems like the best option.
