### ISSUE TITLE
Explain effect of timezone in `date()` API example

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1173]
The current example in https://www.rethinkdb.com/api/python/date/ can have confusing behavior when timezones are involved, see https://github.com/rethinkdb/rethinkdb/issues/6081

**Comment by skinkie** [comment]
@danielmewes are you aware that the example given actually results into:

```
>>> r.now().run(conn)
datetime.datetime(2016, 9, 19, 20, 23, 1, 720000, tzinfo=<rethinkdb.ast.RqlTzinfo object at 0x7f9737c1c5d0>)
>>> r.now().inTimezone("+02:00").run(conn)
```
