### ISSUE TITLE
Two failing links in README.md when viewed in GitHub

### ISSUE THREAD

**Issue by jheyne** [rethinkdb/docs#1197]
There are two failing links in README.md when viewed in GitHub – perhaps related to the way default links are now generated for .md files.

#1 – “`The documentation for the latest RethinkDB release is always available at [rethinkdb.com/docs]()` “
  The generated link is: `https://github.com/rethinkdb/docs/blob/master `  (which results in page not found)
  Proposed change: `[rethinkdb.com/docs]( http://rethinkdb.com/docs)`

#2 – “`...and visit [http://localhost:4000]() in your browser.`”
  The generated link is: `https://github.com/rethinkdb/docs/blob/master`   (which results in page not found)
  Proposed change: `[http://localhost:4000]( http://rethinkdb.com/docs)`

These minor flaws caught the attention of our folks who approve software for company use. A change for at least the first point would be welcome.

**Comment by chipotle** [comment]
I think these should probably be self-linking URLs (e.g., `<http://rethinkdb.com>`); I'm not sure why they were set up the way they were. (Going to `localhost:4000` is correct, by the way, since it's supposed to take you to the local build of the docs. Not that I'm positive that works…)
