### ISSUE TITLE
TypeError: r.table(...).get_all is not a function

### ISSUE THREAD

**Issue by jarekkowol** [rethinkdb/docs#1203]
Someone understands what's going on? I will add that I have created a secondary index on the table.

![image](https://cloud.githubusercontent.com/assets/4691971/26034140/250faf6a-38b8-11e7-8901-132bfb69b225.png)

Second problem:

![image](https://cloud.githubusercontent.com/assets/4691971/26034150/5adca9b8-38b8-11e7-9710-1bea4ebc3c9e.png)

If i execute this code in nodejs i have the same issue.

**Comment by chrisvariety** [comment]
Hi @jarekkowol, it's `getAll` in JavaScript: https://www.rethinkdb.com/api/javascript/get_all/

**Comment by jarekkowol** [comment]
I was on a python.. thanks.
