### ISSUE TITLE
add reql pro to third party administration tools

### ISSUE THREAD

**Issue by brutalcrozt** [rethinkdb/docs#1215]
Once upon a time Daniel [say](https://github.com/rethinkdb/rethinkdb/issues/1592#issuecomment-247123082) .
> [ReQLPro](http://reqlpro.com) provides a data browser for RethinkDB 
> It also allows you to update values in-place by double-clicking them in the table view.

I like update the third-party list, with add reqlpro section
cc @csndra0504, @grailian

**Comment by chipotle** [comment]
Closed in #1216

**Comment by csndra0504** [comment]
Thanks! @brutalcrozt 🙏
