### ISSUE TITLE
RethinkDB python

### ISSUE THREAD

**Issue by ouroboroscoding** [rethinkdb/docs#1234]
The documentation is no longer correct. As of version 2.4.1 of the python driver this:

`import rethinkdb as r`

No longer works as expected. The driver docs on pypi state you need to do this instead.

`from rethinkdb import RethinkDB`
`r = RethinkDB()`

Except, this only fixes one problem by introducing a second one, as references to something like `r.errors.RqlDriverError`, or `r.errors.ReqlOpFailedError`, etc, will no longer work and are in fact innaccesible with the suggested fix.

**Comment by srh** [comment]
Noted.  This looks like a serious issue.

**Comment by gabor-boros** [comment]
@srh and @ouroboroscoding I'll adjust the python related documentation on Thursday.

**Comment by gabor-boros** [comment]
The issue has been fixed by @eqladios on 18th of March and deployed to production around a month ago.
