### ISSUE TITLE
Related commands link is broken

### ISSUE THREAD

**Issue by gabor-boros** [rethinkdb/docs#1251]
The related commands links are broken and not containing the driver language context on API descriptions.

**Comment by yaneony** [comment]
If that would help, some description.

Two same links, https://rethinkdb.com/api/javascript/eq_join/ and https://rethinkdb.com/api/javascript/eq_join (doesn't matter JS or Java or Ruby...).

If trailing slash is provided, "Related commands" at the bottom working fine. If there is no slash, links are broken.

**Comment by gabor-boros** [comment]
Resolved.
