### ISSUE TITLE
State that 2.4 is not shipped for windows yet

### ISSUE THREAD

**Issue by gabor-boros** [rethinkdb/docs#1258]
Windows is not supported (yet) in 2.4.0. We need to state that 2.3.6 is the current latest version for windows!

**Comment by gabor-boros** [comment]
I've removed windows from the install list, also added a notification to https://rethinkdb.com/docs/install/windows which states the following:

> The Windows port of RethinkDB is not available for the 2.4.0 version yet. As an alternative, you can use the docker based version.

**Comment by ferrlen** [comment]
Given that currently it isn't possible to build RethinkDB 2.4.x on Windows from source, would it make sense to also add a note there saying this isn't possible? I just lost an entire day trying to build it, and it seems [I'm not the only person](https://github.com/rethinkdb/rethinkdb/issues/6936) to have tried that. Thanks!
