### ISSUE TITLE
Make doc site more readable

### ISSUE THREAD

**Issue by tylergannon** [rethinkdb/docs#1306]
Just a simple request, for the benefit of persons whose eyesight is not very acute, I'd like to ask you to increase the contrast on your web site, between the base font and the background.

I normally don't do this but I spent a minute on your site asking myself "why is this thing so hard to read" before noting that your font is both slim and colored somewhat lightly, and your background isn't helping the matter.

If it helps to set a standard, Github's web site also features fonts so I tend to keep `Dark Mode` enabled so that I can read it better, but your web site doesn't offer that.

thanks!

**Comment by srh** [comment]
It might be that the changes are already committed to the repository, but the website didn't get updated properly.  I'll look into it tomorrow, I hope, when my brain is actually working.

**Comment by srh** [comment]
I just cfa8155edd78830a7be75c8d899599f8f0c7d047 in rethinkdb/www.  That's the last use of `#647276`.  Didn't test locally or anything... Maybe that will do it.

**Comment by srh** [comment]
@tylergannon How do you like it now?

**Comment by srh** [comment]
I'm closing because this is, generally speaking, done.  The website and docs use solid black for most of the text.

Some other colored text is still kind of questionably low in constrast, but we can see if anybody complains about it.
