### ISSUE TITLE
Make error on Ubuntu 20.04  on rethinkdb 2.4.1

### ISSUE THREAD

**Issue by periurium** [rethinkdb/docs#1323]
Stack currently is Ubuntu 20.04 amd64
RethinkDB 2.4.1

followed the instructions on the RethinkDB website up to the build commands. 
upon running `make` 

I received this error:

`
[1/282] CC build/release/obj/clustering/table_manager/table_meta_client.o
c++: fatal error: Killed signal terminated program cc1plus compilation terminated.
make[1]: *** [src/build.mk:379: build/release/obj/clustering/table_manager/table_meta_client.o] Error 1
make: *** [Makefile:53: make] Error 2
`

**Comment by gabor-boros** [comment]
The scope of this issue for resulution is to update the website instructions.

**Comment by srh** [comment]
The website has been updated at https://rethinkdb.com/docs/install/ubuntu/ .  We no longer need `CXX=clang++` but the instructions are updated with other changes like `python3`.
