### ISSUE TITLE
Term 'point-replace' is used, but not defined, in replace() docs. 

### ISSUE THREAD

**Issue by mikemaccana** [rethinkdb/docs#133]
From http://www.rethinkdb.com/api/javascript/replace/:

> You can have new documents inserted if you do a point-replace on a key that isn't in the table

I'm not sure what 'point-replace' means, and I can't find a definition for this term on rethinkdb docs or elsewhere on the internet. 

If 'point-replace' just means 'replace', then it might be better to simply use 'replace'.

**Comment by chipotle** [comment]
The page has been edited subsequently to the point where this document isn't relevant (we don't use "point-replace" here anymore).

**Comment by mikemaccana** [comment]
Rad! Thanks.
