### ISSUE TITLE
Document upgrade and downgrade processes

### ISSUE THREAD

**Issue by zamazan4ik** [rethinkdb/docs#1341]
Hi.

After reading the documentation it is not clear for me, how upgrade and downgrade processes should be performed over the database. Could you please describe somewhere in the documentation:

- How to upgrade the database to the newer version (hopefully with no downtime)
- How to downgrade the database to the older version (hopefully with no downtime)
- Maybe some compatibility policies and notes between versions

Thanks in advance!

**Comment by srh** [comment]
I've transferred this issue to the docs repo.

**Comment by srh** [comment]
@zamazan4ik I have made some changes in #1342.  I've merged the changes instead of waiting for feedback, but if you think it could use more clarification, feel free to let me know.

**Comment by zamazan4ik** [comment]
@srh Now it is a much more clear! If you have finished adding the information to the documentation, feel free to close the issue.

Thanks a lot for the changes.

**Comment by srh** [comment]
Okay, I will close.
