### ISSUE TITLE
Docs about backup should mention that we don't dump cluster settings

### ISSUE THREAD

**Issue by neumino** [rethinkdb/docs#141]
We should say it on this page
http://rethinkdb.com/docs/backup/

**Comment by chipotle** [comment]
@danielmewes - is this still true, after the more recent changes? If it is still true, is there any advice to give people about how to save and restore cluster settings (e.g., scripts using administration commands to reconfigure servers)?

**Comment by danielmewes** [comment]
@chipotle That's still true.

People could theoretically take the output of `r.db('rethinkdb').table('table_config')`, and then try to write those documents back into the new cluster. That's somewhat fragile though, depends on all server names to match, and I think you will have to remove secondary index entries from the documents before writing them back or you will get an error. 

I think it's enough to mention the limitation for now.
