### ISSUE TITLE
Revisit Rethink v Mongo comparison

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/docs#149]
I searched for Ruby v Python comparison and found this: http://c2.com/cgi/wiki?PythonVsRuby. I like their approach much better than ours. Here is the anthology they used:

* Overview
* Heritage and Philosophy
* Popularity
* Readability
* Ease for Beginners
* Ruby Blocks and Python Lambdas
* Development Environments
* Community and Documentation
* Libraries, Platforms and Applications
* Performance
* Opinions : Leaving Python for Ruby / Leaving Ruby for Python (anybody?)
* Misc.

This might not work for us exactly, but it seems like a really good place to start.

**Comment by danielmewes** [comment]
Comparisons to MongoDB are overrated.
