### ISSUE TITLE
Language consistency across guides

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#151]
The [secondary indexes](http://www.rethinkdb.com/docs/secondary-indexes/) guide uses Python, but this isn't a consistent language choice across other guides.

Since the Data Explorer uses JavaScript, we should seriously consider making all guides use JavaScript by default.

An alternative would be to make all guides multi-language, which is more effort.

**Comment by danielmewes** [comment]
I think this is mostly not an issue anymore. We should open more specific issues when this is a problem for a specific page.
