### ISSUE TITLE
Add docs to help contributors get started

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/docs#154]
We make contributing to RethinkDB really hard because potential contributors get no guidance. Here is some stuff we could do:

* Describe rough categories in how people can contribute
* For each category provide some basic getting started docs
* For each category point people to some issues they could begin with (say, simple, medium, and advanced)
* Have a system where contributors can get some time from a mentor to help them learn the ropes

We'd really have to integrate all this into our culture, and perhaps it's not the right time yet, but it's something we should at least think about.

**Comment by danielmewes** [comment]
We have some of this in the READMEs of the repositories now.
