### ISSUE TITLE
Document programmatic cluster administration

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/docs#156]
The `rethinkdb admin` tool is undocumented on the website, and users are having trouble with figuring out how to administer clusters when manual administration isn't feasible (see https://github.com/rethinkdb/rethinkdb/issues/1792 for an example set of questions).

We should have a page "Programmatic cluster administration" (or something of the sort) in the docs that gives a primer for `rethinkdb admin`.

**Comment by danielmewes** [comment]
Closing because this is outdated.
