### ISSUE TITLE
Troubleshooting - RqlDriverError: Nesting depth limit exceeded

### ISSUE THREAD

**Issue by neumino** [rethinkdb/docs#162]
We should mention:
- The limit which is set to 20
- And that in practice, it means there is a circular reference somewhere.

**Comment by chipotle** [comment]
What would an example of a circular reference in ReQL be that's likely to come up in practice? I understand the concept of "circular reference" but I can't envision how you get that situation in a ReQL query.

I've tried to search for cases where this has happened in the wild, and it looks like people have triggered this error with deeply nested JSON objects, at least long ago (http://www.irclogger.com/.rethinkdb/2013-12-26).

**Comment by danielmewes** [comment]
@chipotle you can do something like this in Python:
```py
import rethinkdb as r
o = {}
o["e"] = o
r.expr(o)
.... throws the mentioned RqlDriverError
```

I don't think this is the typical case though. I agree that it's at least equally likely that users run into this because of objects or arrays that are simply deeply nested.
