### ISSUE TITLE
Add an example application / getting started guide for Rails

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#21]
Suggested by krz on IRC:

> &lt;krz> is there a getting started guide for rails applications?
> &lt;krz> you guys should really come up with a rails demo app using the ruby wrapper
> &lt;krz> just thought, if there was a guide up, just to get integrated with rails. that would be awesome

**Comment by chipotle** [comment]
We not only have a link to NoBrainer, we have a page about it called "Using RethinkDB with Ruby on Rails." That was only linked from the "Third-Party Integrations" page but I've re-added it as "RethinkDB and Rails" under "Integration."
