### ISSUE TITLE
We should add a doc section for driver developers

### ISSUE THREAD

**Issue by jdoliner** [rethinkdb/docs#24]
I'm not quite sure where this fits into your guys scheme but I think there should be a section in here somewhere to get driver developers started. One thing in particular that I think would be good to include is a rundown of optimizations we make in our drivers to get better performance such as converting to JSON and deserializing values lazily.

**Comment by chipotle** [comment]
We have a "Writing Drivers" document. Specific problems/requests for enhancement in that should get more specific issues opened (e.g., #768).
