### ISSUE TITLE
Improve the driver protocol spec

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/docs#355]
As of the time of this writing, it's here -- https://github.com/rethinkdb/rethinkdb/blob/mlucy_proto_docs/src/rdb_protocol/ql2_json.md, but will be on the site soon.

Here are some things that need to be improved:

- [ ] Section 2 (the query) needs to be expanded. Right now it's as long as section 1 (the handshake), but the mechanics are significantly more complicated, and we let people guess a lot. In particular, we should have a few more progressively more complex examples (start with r.expr(1) and show how to use lambdas and such), and explain how the json protocol related to protobufs a bit better. For example, we link to the protobuf spec, but don't even say that you're supposed to use the integer values defined there explicitly.
- [ ] Add a section at the end that gives people some friendly notion on how to get started. For example, we should explicitly link to the official drivers, and a few community drivers source code.

**Comment by mlucy** [comment]
Unassigning myself because I'm not sure what I'm supposed to be doing on this issue.  I think this eventually made it onto the site, right?

**Comment by coffeemug** [comment]
Yes, this is on the site. We should write a separate tutorial at some point that walks people step by step on how to create a sample driver.

**Comment by danielmewes** [comment]
From what I can see @neumino's comments from here https://github.com/rethinkdb/docs/pull/358/files are still not reflected in the docs. So we should keep this open.

Another thing I've just noticed is that we don't link to the new document from http://rethinkdb.com/community/ (not sure if this is going to be redone anyway for 2.0? @mglukhovsky?).
> Write a new driver — no ReQL driver for your favorite language? Help write one! Hop on the mailing list or #rethinkdb on freenode, and we'll walk you through the driver protocol API.

still just links to the ql2.proto file.
http://rethinkdb.com/docs/install-drivers/ links to the right document (http://rethinkdb.com/docs/driver-spec/) correctly. I think the Community page should also link to that.

**Comment by mglukhovsky** [comment]
Agreed. The community page is being reworked, but you're correct that we should link to that document.

**Comment by danielmewes** [comment]
These have been improved a lot in the meantime.
