### ISSUE TITLE
Jekyll with only the docs repository

### ISSUE THREAD

**Issue by neumino** [rethinkdb/docs#404]
Reported by @metaflow

```
/home/meta/github/rdb_docs$ jekyll build
Configuration file: none
            Source: /home/meta/github/rdb_docs
       Destination: /home/meta/github/rdb_docs/_site
      Generating... 
  Liquid Exception: Unknown tag 'apibody' in api/ruby/math-and-logic/add.md
```

I also get the same error.

@mglukhovsky -- You were working on a light template for the docs. I think it was working, if it is still working, could we merge your changes?

**Comment by mglukhovsky** [comment]
I've finally gotten around to this: you can build and serve a standalone Jekyll site using the command `rake`. The README will be updated shortly with instructions.
