### ISSUE TITLE
Write docs for driver developers for 1.14

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/docs#452]

**Comment by mlucy** [comment]
Unassigning myself because this seems old and I'm not sure what I'm supposed to do here.  If there's something I'm supposed to be writing, feel free to re-assign to me.

**Comment by danielmewes** [comment]
Assigned @chipotle 
We should bring https://gist.github.com/neumino/5b8339c7f28d665f5900 up to date and make a proper article for our docs out of it.
