### ISSUE TITLE
Document new ReQL admin API

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/docs#464]
The ReQL admin API will need documentation.

Currently it's still in a very early stage of implementation. The implementation will be in the `reql_admin` branch of the rethinkdb/rethinkdb repository, and issues are in the `reql-admin` milestone.

**Comment by chipotle** [comment]
This covers everything that I knew of as of Thursday, 1/15 -- please open new doc tickets for anything that's missing and/or changed since then. (For instance, the `jobs` table isn't documented yet, but I'm not sure that it's finished yet, as rethinkdb/rethinkdb#3115 is still open.)

**Comment by danielmewes** [comment]
Awesome work! :clap:

**Comment by neumino** [comment]
The administration commands are missing from index.md (at least in JS). Is it intended?

**Comment by chipotle** [comment]
That's not intended, no. I'll check that when I get in.

**Comment by danielmewes** [comment]
Good catch @neumino! I guess they will be missing in the DataExplorer auto completion then? We can do a point release shortly after to address that.

**Comment by chipotle** [comment]
Dangit. The index files are committed in a new branch:

https://github.com/rethinkdb/docs/tree/issue-464-index

**Comment by danielmewes** [comment]
Thanks for checking @chipotle . I just merged the branch into v1.16 so we can build the Data Explorer docs. We should double check the changes tomorrow though, since I couldn't find whether they've gone through code review or now.

**Comment by chipotle** [comment]
They haven't -- I just created that branch a half hour ago and I don't have my home laptop set up for CodeReviewer.
