### ISSUE TITLE
API: Python - add docs on inserting native date objects

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#49]
There are currently no docs on using the native Python date objects (see the [tests](https://github.com/rethinkdb/rethinkdb/blob/next/test/rql_test/src/times/shim.yaml#L8) for an example).

**Comment by chipotle** [comment]
The "Dates and times in RethinkDB" document is fully translated into each language now and it tells you how to use native date/time objects. I'd like more explanation about what's meant by "the API docs not having examples for native time objects."
