### ISSUE TITLE
"Cluster on startup" is confusing to new users

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#582]
From an email with @ukd1:

> [Running the RethinkDB service] gives a message saying to go read the docs. Reading the docs, the bit of interest (quick start) hard to find - it is 7 paras + a long long list of options down the page. 

> It notes: "The packages do not ship with a default config file". 

**Here's the problem:**

When you try to start the RethinkDB service (`/etc/init.d/rethinkdb start` or `service rethinkdb start`), but haven't added config files to `/etc/rethinkdb/instances.d`) you see the following message:

```
rethinkdb: No instances defined in /etc/rethinkdb/instances.d/
rethinkdb: See http://www.rethinkdb.com/docs/guides/startup/ for more information
```

The error message is bewildering to new users, especially when you click the link and see a long page of various options, rather than a clear guide.

**We should improve the docs in one (or more) of the following ways:**

  - We should immediately link to a quickstart section that has clear steps for getting up and running, rather than dumping users on a long document.
  - Even better, rather than link to a document that specifies every option for startup scripts (for every init system, for every platform), we should write a gentle guide that clearly links to a doc with the complete specifications.

**The quickstart section also uses very negative language.** Example:

> The packages do not ship with a default config file, so if you install RethinkDB, it will not automatically be run on system startup until you add a config file to /etc/rethinkdb/instances.d/.

This is equally bewildering (what do you mean RethinkDB doesn't ship with a file you need to accomplish the task you want?) We also do ship an example config file that is easy to get started with -- so we should use positive language, for example:

> You can set up an init script to automatically run RethinkDB on startup by adding a config file to /etc/rethinkdb/instances.d/.
>
> Copy the example config file and restart the init.d script:
> <continued>

This is part of the initial curve when getting up and running with RethinkDB, so it needs some love.

@chiptole, thoughts?

**Comment by chipotle** [comment]
I'm closing this ticket in favor of #643 -- it doesn't add an entirely new quickstart document, but it reorganizes a lot of the relevant docs, moves the config file options into their own document and tries to make the language clearer and a little friendlier.

**Comment by thomasmodeneis** [comment]
Hi @chipotle,  I lost few hours on this problem. 
The documentation still not good (http://rethinkdb.com/docs/start-on-startup/), it assumes the person that is reading know anything about rethinkdb, and well it should be the opposite, I don't know anything and I expect that the steps defined will work o.0 
Let me explain: 

```
Quick setup
Copy the sample configuration file and use the configuration file documentation as a guide to customize it. (If you don’t have the sample .conf file, you can download it here.)
```
1) The referenced doc is all commented, how can I know what is or what is not needed ? 
https://github.com/rethinkdb/rethinkdb/blob/next/packaging/assets/config/default.conf.sample

2) if you use the file above and run the commands as described on the following step:
```
sudo cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/instance1.conf
sudo vim /etc/rethinkdb/instances.d/instance1.conf
```
This wont work. Rethinkdb will get me an error after another. 
1 error: the file provided have user and group commented, and it does not explain that this users should be the linux user that will be running the rethinkdb.
2 error will be you need to have the folder created: /var/run/rethinkdb and mkdir /var/run/rethinkdb/instance1
3 error will be you need to have the folder created: /var/lib/rethinkdb/instance1 and the data /var/lib/rethinkdb/instance1/data.
4 error will be this folders all need to be chmod with the user that will be executing the rethinkdb:
sudo chown -R vagrant:vagrant /var/run/rethinkdb

I created a quick shell script that finally made the startup work on my vagrant box, this maybe useful for someone:
```
echo "runuser=vagrant" >> ~/instance1.conf
echo "rungroup=vagrant" >> ~/instance1.conf

sudo mv ~/instance1.conf /etc/rethinkdb/instances.d/

sudo mkdir /var/run/rethinkdb
sudo mkdir /var/run/rethinkdb/instance1

sudo mkdir /var/lib/rethinkdb/instance1
sudo mkdir /var/lib/rethinkdb/instance1/data

sudo chown -R vagrant:vagrant /var/run/rethinkdb
sudo chown -R vagrant:vagrant /var/lib/rethinkdb
```

Thanks

**Comment by danielmewes** [comment]
@thomasmodeneis Thank you for the great feedback.

The init script should actually do all of those things automatically, though I think it defaults to user `rethinkdb` if no other user is defined and depending on how you installed RethinkDB that might not exist.

A few follow up questions:
- Which Linux distribution are you using in your vagrant box?
- How did you install RethinkDB?
- If you only set the runuser and rungroup in the instance file to `vagrant` (in your case) but don't create any folders, what is the error message that you receive?

This could be a problem with our init script more than with the documentation
