### ISSUE TITLE
Server ops/monitoring and changefeeds documentation outlines

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/docs#601]
@chipotle -- here is the outline I was talking about for server ops/monitoring:

- Scale to multiple machines with a simple API
  - Shard and replicate a table in seconds with a simple API (`reconfigure`)
  - Apply replication settings to all tables in a database (`db.reconfigure`)
  - Set up server tags and scale to multiple datacenters
- Fine-grained control of your cluster
  - Query full cluster configuration details (the `table_config` table)
  - Change every last detail by writing to `table_config`
- Detailed insight into cluster status
  - View detailed status of everything in your cluster (`table_status`, `server_status`)
  - Complete view into cluster issues (the `issues` table)
  - Subscribe to status feeds (calling `changes` on system status tables)
- Query cluster statistics 
  - The stats table
  - Using ReQL on the stats table to slice/dice data
- Full control of running jobs
  - The `jobs` table
  - Deleting from the `jobs` table to kill jobs

And here is one for changefeeds:

- View changes on a document in realtime (`t.get().changes()`)
- Set up feeds on fine-grained queries (e.g. `t.between.changes`)
- Aggregation feeds (e.g. `t.orderBy.changes`)
- Latency awareness (the `squash` optarg to `changes`)
- Scale your realtime app (a note on scalability and how many feeds a user can open)
- Tutorials (we should rewrite our intro guides to be feed-centric)

Feel free to take what feels right from these outlines and discard what feels wrong for 1.16. For 2.0, I'd like to do a couple of things:

- Restructure docs hierarchy based on what we learned from users and how they think about the system
- Link into specific doc pages from the landing page (in particular, with streaming/changefeeds, ops/monitoring, and FAQ). Since users will often click on those directly to learn about RethinkDB, we should put a bit more effort into explaining things in a specific way. The guides will also have to be feed-centric. This will be really important because it'll be on the path of users learning about the product.

We can talk about that once 1.16 is out, so I'm putting this issue into 2.0 milestone.

**Comment by chipotle** [comment]
Some of what's in this is already in the documentation -- this is just a matter of reorganization -- and the new outline I'd proposed a while ago has an "Administration" section.

I've updated that outline to show the new sections that were added in 1.16, along with a couple sections that don't exist yet like "Server tags and scaling."

https://gist.github.com/c3a4daf1b7e25fb5b4cd.git

**Comment by chipotle** [comment]
I'm going to fold the first part of this (server ops/monitoring) into #627 and open a separate ticket for enhancing the existing changefeeds document.
