### ISSUE TITLE
Change build instructions to use jemalloc instead of tcmalloc

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/docs#602]
See https://github.com/rethinkdb/rethinkdb/issues/2279

**Comment by danielmewes** [comment]
Just want to make sure this doesn't slip through the cracks.
@AtnNn are you going to take care of this or do you want some help?

**Comment by AtnNn** [comment]
Working on this now.

**Comment by AtnNn** [comment]
New build instructions are up in review. They depend on https://github.com/rethinkdb/rethinkdb/issues/3741 being fixed.

**Comment by AtnNn** [comment]
New build instructions in 6827dd6
