### ISSUE TITLE
Add documentation for new changefeed features

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/docs#605]
* `.between.changes`
* `.orderby.limit.changes`
* `.filter.changes`
* `.map.changes`
* `squash`

**Comment by chipotle** [comment]
@mlucy - since you assigned this to yourself I figured you intended to write up a little bit about these yourself first and then bounce that to me?

**Comment by chipotle** [comment]
Re-assigning back to me, as @mlucy wrote up some docs for `squash`. Are the other mentioned points things that need to be documented beyond a note in the `changes()` documentation about working with those commands now?

**Comment by danielmewes** [comment]
@mlucy suggested a few days ago that we could put an example or note about changefeeds in the documents of the commands that you can apply `changes()` to.

For example we could add an example with `changes()` to the documentation of the `max` term, or to `get` ("... You can also listen to changes on a document by opening a changefeed: r...get(...).changes()").

I don't think this is necessary before the 1.16 release though. We can extend the documentation in that respect later.

I think apart from documenting the `squash` parameter, noting the now working combinations in the `changes()` docs is the only critical thing.

**Comment by danielmewes** [comment]
What's the state of this @chipotle ?
