### ISSUE TITLE
Restructure the `filter` documentation page by theme

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#609]
`filter` is a fairly subtle command for new users to understand, which is why there are so many examples included on its [documentation page](http://rethinkdb.com/api/javascript/filter/). However, it's currently just a list of examples -- it would be far better to organize the examples by theme, for example:

- Basic filters
- Filtering multiple attributes using boolean logic
- Handling missing fields
- Passing functions to filter (advanced predicates)
- ... and others

__Note__: one example is missing. It's a relatively special case, but should be documented in the "Handling missing fields section" once this is reorganized so that it's not just a giant wall of examples:

If you use an `or` predicate, you need a `default` after the first condition to ignore missing fields in the first part of the condition (see http://stackoverflow.com/questions/27682642/rql-or-not-work-while-involving-non-exists-field/27682774#27682774)

**Comment by danielmewes** [comment]
Just noticed that we currently document the `or` non-existence question in our "Troubleshooting" article http://www.rethinkdb.com/docs/troubleshooting/#filters-with-or-return-incorrect/unexpected-r

It still should be included in the `filter` docs I think.

**Comment by mglukhovsky** [comment]
Awesome, good work @chipotle!
