### ISSUE TITLE
python help for r.binary includes markdown 

### ISSUE THREAD

**Issue by larkost** [rethinkdb/docs#611]
The help text that comes from `help(r.binary)` in the python driver includes markdown links that are nonfunctional, e.g.:

<pre>
    * [coerce_to](/api/python/coerce_to/) can coerce `binary` objects to `string` types
    * [count](/api/python/count/) will return the number of bytes in the object
    * [slice](/api/python/slice/) will treat bytes like array indexes (i.e., `slice(10,20)` will return bytes 10&ndash;19)
    * [type_of](/api/python/type_of) returns `PTYPE<BINARY>`
    * [info](/api/python/info) will return information on a binary object.
</pre>

We should either reformat this to include full links, or suppress the link parts.

**Comment by chipotle** [comment]
There are a *lot* of places in the API documentation where this shorthand is being used. What happens in the other cases? Changing them from relative links to fully-qualified ones might be better handled by the Python help documentation build script.

**Comment by chipotle** [comment]
Pinging @larkost on this, when you get a chance -- I think this might be something to change in the Python script. (I might be able to make that change, but not without querying you about whether that's a terrible idea first.)

**Comment by larkost** [comment]
Nope, that sounds like the correct approach given how we generate documentation for Python.

**Comment by chipotle** [comment]
A change to the script which appears to work is in CR 2550.
