### ISSUE TITLE
Document --no-default-bind option

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#612]
1.16 will come with a new `--no-default-bind` command line option that disables binding to loopback interfaces (unless explicitly specified in a separate `--bind` or through `--bind all`).

(lengthy discussion about it in https://github.com/rethinkdb/rethinkdb/issues/3154)

**Comment by chipotle** [comment]
I'm rolling this into #613 since it's already part of the new `cli-options` document being added.
