### ISSUE TITLE
Document --no-update-check option and which data we send by default

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#613]
1.16 will have a new `--no-update-check` command line option to disable
a) update notifications in the server log
b) transmitting anonymized usage statistics to RethinkDB

Related issue: https://github.com/rethinkdb/rethinkdb/issues/3170

We also have to document which data exactly is transmitted. I think the FAQ http://rethinkdb.com/faq/ are a good place for this.

In the current implementation, this is the data we transmit:
* RethinkDB version
* Number of servers in the cluster
* The operating system (Linux or OS X) and architecture (32 or 64 bit)
* Number of tables, heavily rounded to the order of magnitude, namely `2^(round(log_2(num_tables)))`

**Comment by chipotle** [comment]
Closed in d63225d9ef182cc89c482713321cc236f9b94137.
