### ISSUE TITLE
indexCreate() docs should mention potential for a raised error

### ISSUE THREAD

**Issue by christiank** [rethinkdb/docs#617]
The documentation for `tableCreate()` notes that if you try to create a table that already exists, the client driver will raise RqlRuntimeError.

The documentation for `indexCreate()` does _not_ mention this, so I assumed it was a silently idempotent operation. Turns out that's not true -- `indexCreate()` actually behaves identically to `tableCreate()`. I like that the functions themselves are consistent, but the docs don't really communicate that IMHO.

I suppose this issue could apply to _all_ ReQL commands which behave in this way, too.

**Comment by danielmewes** [comment]
Thanks for reporting this @christiank .
In the short term, we should do as you say and document that `indexCreate()` just like `tableCreate()`, fails if the index already exists.

In the long term we should document all major error cases for *all* of the ReQL terms. I thought we already had an issue for that, but I cannot find it at the moment (@chipotle do you remember anything like that?). It might make sense to wait doing this until we have a better exception type hierarchy (https://github.com/rethinkdb/rethinkdb/pull/2103).
