### ISSUE TITLE
Prominently mention download.rethinkdb.com in the build instructions

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#619]
The [build instructions](http://rethinkdb.com/docs/build/) don't mention that we host tarballs of all past versions at [download.rethinkdb.com](http://download.rethinkdb.com).

@kofalt mentioned this in rethinkdb/rethinkdb#3544:

> When I went to go check how blind I was, the link is mainly talking about older versions (and does not talk specifically about the dist tarball folder).

> Maybe linking to that on the 'building from source' pages would be useful.

and:
> Specifically mentioning

> >They contain pre-compiled platform-independent assets and pre-fetched dependencies.
> As that's excessively relevant.

We should mention it prominently on the build instructions.

**Comment by AtnNn** [comment]
Duplicate of https://github.com/rethinkdb/docs/issues/325

**Comment by chipotle** [comment]
If the distribution tarballs contain pre-fetched dependencies, does that mean that starting by downloading one of them eliminates the need to follow the "get the build dependencies" and "get the source code" sections in the current build directions?

**Comment by AtnNn** [comment]
See #325. The "get the source code" section can be replaced by wget/untar and the build dependencies section is still required, but can be trimmed. I plan on doing this myself.
