### ISSUE TITLE
Document jobs table

### ISSUE THREAD

**Issue by chipotle** [rethinkdb/docs#624]
Per rethinkdb/rethinkdb#3115, the job control API through the `rethinkdb.jobs` table needs to be documented for v1.16.

**Comment by danielmewes** [comment]
Yeah even though the issue is still open (because there are some additional features for future releases), the jobs table is done for 1.16.

**Comment by danielmewes** [comment]
@VeXocide can help you with the details.

**Comment by VeXocide** [comment]
Of course, I'll give a list with some example jobs and a bit of explanation, though most should be self-explanatory.

**Comment by VeXocide** [comment]
For each job there's a duration in seconds in `"duration_sec"`, an `"id"` consisting of the `"type"` and a unique id, a list of servers involved in `"servers"`, and the type of the job in `"type"`.

```
{
    "duration_sec": 5.852541 ,
    "id": [
        "query" ,
        "6fae89ba-09bd-45bb-a74b-623cfc9b3d89"
    ] ,
    "info": {
        "client_address": "192.168.0.1" ,
        "client_port": 50062
    } ,
    "servers": [
        "newton_hk3"
    ] ,
    "type": "query"
}
```

`"disk_compaction"` is an ongoing process on each server, hence the duration `null`, and is primarily listed to explain IO utilization of a machine.
```
{
    "duration_sec": null ,
    "id": [
        "disk_compaction" ,
        "ef400d70-904a-5285-bcf9-a62419a0770b"
    ] ,
    "info": { } ,
    "servers": [
        "newton_hk3"
    ] ,
    "type":  "disk_compaction"
}
```

`"index_construction"` is the construction of an index `"info"."index"` on database `"info"."db"`, table `"info"."table"` with `"info"."progress"` being a double between zero and one.
```
{
    "duration_sec": 10.6485 ,
    "id": [
        "index_construction" ,
        "2d142757-54f8-5d6f-916e-0bd38fe57813"
    ] ,
    "info": {
        "db": "test" ,
        "index": "x" ,
        "progress": 0.5297221273063037 ,
        "table": "test"
    } ,
    "servers": [
        "newton_9m0" ,
        "newton_hk3"
    ] ,
    "type": "index_construction"
}
```

**Comment by danielmewes** [comment]
Looks like you've done this @chipotle ?

**Comment by chipotle** [comment]
Yep, this is done. I have to manually close it because it's not in the master repository.
