### ISSUE TITLE
extra server troubleshooting info available for 1.16

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/docs#625]
> What's wrong with my server?

Troubleshooting a problem remotely is often a tedious interview that lasts until there is enough information to figure out the problem. The new ReQL admin API in 1.16 can help with this, just ask this question first:

> `r.expr(["current_issues","db_config","jobs","server_config","server_status","stats","table_config","table_status","cluster_config"]).map([r.row, r.db('rethinkdb').table(r.row).coerceTo('array')]).coerceTo('object').merge({'logs':r.db('rethinkdb').table('logs').limit(50).coerceTo('array')})`?

It will return a dump of the `rethinkdb` system database, with truncated logs and the `auth_key` removed, giving you enough information to troubleshoot common problems.

**Comment by danielmewes** [comment]
Neat. We should also update http://rethinkdb.com/docs/crashes/ "How to submit a bug report" with that.

As a small simplification, it's not really necessary to remove the auth key, since all you get from the `cluster_config` table is a boolean whether the auth key is set or not.

**Comment by AtnNn** [comment]
Ah, that's even better. I'll update the query. I don't have an auth key, and I get `null` not `false`, so I assumed it would

**Comment by danielmewes** [comment]
If you set an auth key, you get `auth_key: {hidden: true}`.

**Comment by AtnNn** [comment]
Another table that would be useful to add to the query is `_debug_table_status`.
