### ISSUE TITLE
Confusing wording in the FAQ

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/docs#633]
joseraul mentioned on HN (https://news.ycombinator.com/item?id=8974322) the following quote from the FAQ:

> "For multiple document transactions, RethinkDB favors data consistency over high write availability. While RethinkDB is always CID, it is not always A."

This sentence is confusing because ACID has nothing to do with CAP. We should rephrase it so it's clear. Assigning to self as I'll be rewriting the FAQ for 2.0.

**Comment by chipotle** [comment]
I think we should probably make a temporary "fix" for this, given that it's not exactly incorrect but kind of mangled. How about replacing that FAQ answer with something more like:

> Most write operations involving a single document in RethinkDB are guaranteed to atomic. Operations that are not deterministic cannot update documents in an atomic fashion (such as random values, or values obtained as the result of a subquery). In addition, multiple documents are not updated atomically.

This uses language much closer to the architecture document.

**Comment by coffeemug** [comment]
:+1:
