### ISSUE TITLE
add launchd documentation to the `cluster-on-startup` page

### ISSUE THREAD

**Issue by larkost** [rethinkdb/docs#638]
There are currently no explicit instructions for MacOS/launchd on [our `cluster-on-startup` page](http://rethinkdb.com/docs/cluster-on-startup/). We should probably add this case to the documentation.

**Comment by danielmewes** [comment]
Do we need to provide a special script or can launchd be made to use our SysV init script?

**Comment by larkost** [comment]
With launchd it is only a configuration document, not a script. So it would be different.

**Comment by mglukhovsky** [comment]
It might be good to mention [lunchy](https://github.com/eddiezane/lunchy) as a friendly wrapper for `launchctl`.

**Comment by chipotle** [comment]
I'm going to wait until #643 gets through code review to tackle this. Do we include a .plist file for `launchd`? If not we can probably use Homebrew's as a reference point. (And perhaps recommend that people install through Homebrew, or at least mention it?)
