### ISSUE TITLE
Underscores badly parsed in "System current issues table"

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#646]
![screen shot 2015-02-09 at 2 22 33 pm](https://cloud.githubusercontent.com/assets/91193/6117178/c1709472-b067-11e4-9e54-9c53a5dbebc7.png)

The underscores in the name `table_needs_primary` are being misrendered. Shouldn't table names always use backticks (i.e. code styles?)

**Comment by chipotle** [comment]
Table names do use backticks, but "table_needs_primary" isn't a table name, it's a possible field value. This is a Markdown rendering issue I didn't catch. (Some Markdown renderers, like Github's and Discount, don't switch to italics for underscore characters inside words, but I'd forgotten ours does.)

**Comment by mglukhovsky** [comment]
@chipotle: we're moving to Kramdown, which is a lot more configurable in behavior and more well-defined, which should reduce a lot of these kinds of bugs.

**Comment by chipotle** [comment]
Quick fix in 27d2034eafc7b0b75ef2d3b69b77d9a626ff80e0, verified and pushed.
