### ISSUE TITLE
Document that we support `.union.changes` and `.get_all.changes` in 2.0

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/docs#653]

**Comment by chipotle** [comment]
Do either of these changefeeds return an initial value?

**Comment by mlucy** [comment]
@chipotle -- sorry, missed your question until now; `.get_all.changes` doesn't return an initial value, and union just does whatever the things you're unioning does (so if you union two `.orderby.limit` streams, it will return an initial value, if you union two `.table` streams it won't).
