### ISSUE TITLE
The order of the related commands can change when rebuilding.

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/docs#657]
I've put a patch in review.

With this patch, the build seems deterministic. It is possible to diff two builds and see the differences. For example I use these commands in the www repo:

```
rm -rf _site_base; rake build; mv _site _site_base; (cd docs; git checkout test); rake build subs=no
diff -ur _site_base _site | diff-highlight | less
```

**Comment by chipotle** [comment]
I don't think this ticket is relevant with the new site build.

```
rake build
mv _site ~/site-1
rake build
ksdiff _site ~/site-1
```

Shows no difference. (`ksdiff` is a third-party diff tool.) We can re-open if it seems there's really a problem here/still.
