### ISSUE TITLE
nth, get_field and bracket

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/docs#659]
A few versions ago we added a `bracket` term, that supersedes both `get_field` and `nth`.

The documentation still calls `()` and `[]` `get_field` (http://rethinkdb.com/api/javascript/get_field/)

It should perhaps be renamed to `bracket`, and mention that it accepts array offsets as an argument, just like `nth`.

**Comment by danielmewes** [comment]
If we rename the document tag from `getField` to something else we also need to adapt `admin/static/coffee/dataexplorer.coffee` in the `rethinkdb` repo since it has special handling for `getField`.

**Comment by chipotle** [comment]
Do we want to change both the documentation and the `dataexplorer.coffee` file, or leave it referred to as `get_field` but update it to mention the array offset case?

**Comment by danielmewes** [comment]
I think we should change the tag to `bracket` as well.
It's not actually much work to update `dataexplorer.coffee`. Basically we just need to grep for get_field (or getField) and replace it by bracket in there.
