### ISSUE TITLE
Typo in map-reduce article

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#661]
In the [map-reduce article](http://rethinkdb.com/docs/map-reduce/):

> We'll also add a "count" field set to 1; we'll use this the same way we used the mapping of each post in the blog example.
> ...
> `...'quantity': item['quantity']. 'count': 1}`

which should be:

> `...'quantity': item['quantity'], 'count': 1}`

**Comment by danielmewes** [comment]
For others having difficulties spotting the difference like me: there is a period after `item[...]` instead of a comma.
