### ISSUE TITLE
Maintain LTS (2.0) version of API docs

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#665]
Once we have 2.0 out, we need to keep supporting 2.0 API docs even after releasing newer server versions (2.1 and following).

@mglukhovsky mentioned at some point that there will be a place in the new website for version information.

The other part of that question is how different versions of a document can be maintained in the docs repository and how we're going to deploy them (separate folders, separate files, maybe just a separate branch?).

In the simplest case we would simply add annotations to ReQL terms and optargs that mark in which release those terms/optargs were added. However that doesn't work too well if we change the behavior of an existing term.

**Comment by deontologician** [comment]
I think branches might be nice, so we can easily compare across versions. The build process could just have a list of branches it will build docs for and the end result would keep them in separate directories for serving

**Comment by chipotle** [comment]
Internally, the separate branches seem like the best idea.

The way a fair number of other projects seem to do this externally is to include the version number in the URL:

    http://rethinkdb.com/api/2.0/javascript/run

with symlinks set up so there's always a `current` version available (or using URL rewriting to do that):

    http://rethinkdb.com/api/current/javascript/run

I imagine the deployment/build script could check out the branches in the right place, create the symlink, etc. I don't know if we'd want to keep deploying by building the entire web site locally and then rsyncing to production, though.

**Comment by chipotle** [comment]
Pinging @mglukhovsky for thoughts on this.

**Comment by mglukhovsky** [comment]
@watts: I've added this to my website TODO list, I need to give this some thought. Thanks for the ping!

**Comment by danielcompton** [comment]
I'm a big fan of how Basho does their documentation, it's always really clear which version you're looking at and how to look at older versions. https://github.com/basho/basho_docs

**Comment by danielcompton** [comment]
Relates to #778

**Comment by AtnNn** [comment]
Are there any plans to do this before 2.1?

**Comment by danielmewes** [comment]
@AtnNn Yes, @mglukhovsky has been working on something.

**Comment by chipotle** [comment]
This is being handled now, so we can close the issue, I think.
