### ISSUE TITLE
Docs about table_status

### ISSUE THREAD

**Issue by neumino** [rethinkdb/docs#667]
I couldn't find any documentation about table_status, especially the `status` returned besides the issue itself https://github.com/rethinkdb/rethinkdb/issues/2983

**Comment by neumino** [comment]
Err actually I was more interested in `server_status` but the issue applies for both tables :)

**Comment by neumino** [comment]
I'm trying to build a connection pool, that from time to time queries `r.db('rethinkdb').table('server_status')` to connect to new servers as they are added and remove the one that were declare dead.

This doesn't always work in case of firewalls and such, but for now, I would like to solve the case when the driver is on the same network as the RethinkDB instances.

How can I get a list of addresses to use to connect to?
I retrieve a list of canonical address to use per server. Can RethinkDB provide the address it used to connect to this server as the first one? Or the less local?

**Comment by chipotle** [comment]
The [system tables](http://rethinkdb.com/docs/system-tables/) document describes the structure of `table_status` and `server_status`.

**Comment by neumino** [comment]
Arg I missed that, thanks @chipotle!
