### ISSUE TITLE
Missed cursor.next section for ruby

### ISSUE THREAD

**Issue by aderyabin** [rethinkdb/docs#668]
The section exists for JS - http://rethinkdb.com/api/javascript/#next, for Python http://rethinkdb.com/api/python/#next but not for ruby

**Comment by chipotle** [comment]
The cursor.next() command doesn't exist for Ruby in the current release, as far as I know -- you can iterate through `each`. But (spoiler alert) it's coming soon.

**Comment by aderyabin** [comment]
Yes, `each` is ruby way. But `cursor.next` is also [available](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/ruby/lib/net.rb#L115)

**Comment by chipotle** [comment]
I'm pretty sure that's the "coming soon" part. :) That's the development branch, but it's not in the production release yet.

**Comment by aderyabin** [comment]
okey.
