### ISSUE TITLE
table_list api docs have an empty bullet point in the Related commands section

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/docs#687]
http://rethinkdb.com/api/javascript/table_list/

I looked at the source, and it seems tableDrop and tableCreate are supposed to be there, but it isn't being rendered for whatever reason. Maybe it's a syntax error or something in the yaml header

**Comment by deontologician** [comment]
edited the title, it's table_list, not db_list

**Comment by deontologician** [comment]
Ok, I just realized it seems none of these are rendering for any api page

**Comment by deontologician** [comment]
ping @chipotle

**Comment by chipotle** [comment]
Well, that's fascinating. I've deployed the site and they're back now.
