### ISSUE TITLE
Bump minimum preferred community driver version

### ISSUE THREAD

**Issue by chipotle** [rethinkdb/docs#688]
Right now, our [driver index page](http://www.rethinkdb.com/docs/install-drivers/) separates third-party drivers into ones that are "updated to at least the RethinkDB v1.11 protocol" and ones that aren't. With 2.0, we should consider switching that from v1.11 to a later version -- at least v1.13, the first one with change feeds.

**Comment by danielmewes** [comment]
We should also require that they support the JSON protocol.
We're going to remove support for that in 2.1.
