### ISSUE TITLE
Add example for conditional upsert

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#694]
Suggested by @thelinuxlich in https://github.com/rethinkdb/rethinkdb/issues/3989

> An example of use case would be a table with created_at and updated_at fields, if the record exists, update only the updated_at field.
> [...]
> 
> ```js
r.table("sessions").get(ID).replace(function(row) {
   return r.branch(row.eq(null), 
       { id: ID,created_at: r.now(), updated_at: r.now() }, 
       row.merge({updated_at: r.now() }
   );
});
```

**Comment by chipotle** [comment]
This sounds more like a cookbook recipe than an additional example for the `replace` command.

**Comment by MarkHerhold** [comment]
I think this should be added to the JS docs as well.

https://github.com/rethinkdb/docs/blob/master/api/javascript/writing-data/replace.md

I was reading the `update` docs and saw an example (called `Example: Perform a conditional update.`) and looked for the same conditional update in the `replace` docs, which was not present, so I assumed that `replace` did not support conditional evaluations. :facepunch:
