### ISSUE TITLE
Wrong and missing information in changefeeds document

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#698]
Feedback from @codepope about http://rethinkdb.com/docs/changefeeds/javascript/:
* between is listed as returning an initial value, but it doesn't (I can also confirm this)
* min, max and orderBy can only be used with changefeeds when they use an index. This should be mentioned.

**Comment by chipotle** [comment]
@mlucy - I just want to check to make sure that this is correct behavior for min/max/order_by with changefeeds.

**Comment by mlucy** [comment]
Both points are correct.  `between` changefeeds can't return initial values (it will be able to in 2.1), and `min/max/order_by` changefeeds require an index.
