### ISSUE TITLE
Better docs for atomicity guarantees in ReQL

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/docs#700]
Right now it's a bit confusing, we could have a list of possible queries which are atomic

**Comment by chipotle** [comment]
The "[Consistency guarantees](http://docs.rethinkdb.com/2.1/docs/consistency/)" document in the upcoming 2.1 release addresses this -- certain *operations* are atomic, but whether or not a *query* is atomic gets more complicated. This document gets into the hows and whys, and gives some advice on how to keep queries atomic.

**Comment by thelinuxlich** [comment]
very good!
