### ISSUE TITLE
New C++ driver

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/docs#702]
I've been working on this lately. I finally got it to pass all the polyglot tests. It might be worth including on the drivers page, it is much more up-to-date than the one that is currently listed.

https://github.com/AtnNn/librethinkdbxx

**Comment by danielmewes** [comment]
The driver looks really awesome @AtnNn. We should definitely include it!
@chipotle

**Comment by chipotle** [comment]
I added this to the new, slightly reorganized 2.0 site, so it should pop up when the new site goes online.
