### ISSUE TITLE
Install page for OS X: "Compile from source" markdown isn't rendered properly

### ISSUE THREAD

**Issue by calesce** [rethinkdb/docs#713]
On the [docs site](http://rethinkdb.com/docs/install/osx/), I see:

![image](https://cloud.githubusercontent.com/assets/5377524/7167729/5a389144-e37d-11e4-85d6-dfe7249e4500.png)

It looks good on the [markdown file on github](https://github.com/rethinkdb/docs/blob/master/1-get-started/install/osx.md). Not sure what's going on the site itself.

**Comment by chipotle** [comment]
Ah ha. The new version of the site we released with 2.0 uses a different Markdown renderer, and in some places it's a little less forgiving than the previous one -- the bug here is that the "```" from the code block and the "# Compile from Source #" don't have a blank line between them. Thanks for catching that!

**Comment by calesce** [comment]
@chipotle no problem, excited to get started!
