### ISSUE TITLE
Document new SSL options for drivers

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/docs#722]
See https://github.com/rethinkdb/rethinkdb/pull/4075 https://github.com/rethinkdb/rethinkdb/pull/4076 and https://github.com/rethinkdb/rethinkdb/pull/4080.

**Comment by danielmewes** [comment]
@neumino voiced concerns that users might see the `ssl` optarg in the API documentation of `r.connect` and assume that the server supports SSL out of the box and be surprised if it cannot connect.
I'm not sure how likely this is to happen (the servers I know with SSL support still all require some configuration to make it work, like installing a certificate etc.), but we should have a comment with the optarg description I think that states that 'Using SSL with RethinkDB requires additional software on the server. [insert link to "how to set up an SSL tunnel" article here]'.
