### ISSUE TITLE
Clarify read consistency guarantees

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/docs#725]
It's possible for reads to see data which has not been written durably to disk. This can lead to some strange situations. For example, the user could send an insert and a read right before a server crashed, and the read could see the inserted document; but then when the server rebooted, the document would not be there. We should document this limitation, perhaps in the "Write acks and durability" section of the "Sharding and replication" page.

**Comment by danielmewes** [comment]
Noting the possibility briefly is a good idea.

I think later for the Raft release we should add a separate article about the guarantees we give in different configurations and provide more details then.

**Comment by coffeemug** [comment]
Ping @chipotle. I think it's important to disclose this limitation in the docs. We should do it asap for various reasons that are far too obvious and numerous to list here (but if you'd still like me to list them, ping me on slack).

**Comment by chipotle** [comment]
OK. Waiting on @coffeemug's edit of @timmaxw's description.

**Comment by coffeemug** [comment]
@chipotle -- sent you an email. I kept Tim's draft, but added one more sentence to indicate that we'll be offering more control soon.
