### ISSUE TITLE
Update documentation for writing drivers to include ResponseNotes

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#729]
Moved from https://github.com/rethinkdb/rethinkdb/issues/4093.

@hamiltop wrote:
> See 62bbf33bed1950103df43ed272458f93f60b7221 
> 
> The documentation on writing drivers still has `SUCCESS_FEED` which no longer exists in master. Ran me around in circles trying to figure out what why `changes()` wasn't returning a `SUCCESS_FEED`.

**Comment by chipotle** [comment]
This needs to be explained to me a little more. :) I see the feed responses are now ResponseNotes rather than ResponseTypes, but I'm going to need a little guidance on what drivers need to do to handle those.

**Comment by danielmewes** [comment]
There are two parts to this:
1. The special `SUCCESS_FEED` and `SUCCESS_ATOM_FEED` (which we already don't mention I think) response types are gone. All changefeeds will instead send the `SUCCESS_PARTIAL` response just like regular cursors.

2. There is a new part of the response, which can be used to figure out if a response is a changefeed or not. This information is often not relevant for drivers (all our official drivers ignore it I think), but it might be used by ORMs or if you want to handle changefeeds and regular cursors differently.
This new part of the response is what we call the "response notes". Each new cursor comes with an array of response notes in its first response. The elements in the response notes array are numbers, with meanings as described here: https://github.com/rethinkdb/rethinkdb/blob/next/src/rdb_protocol/ql2.proto#L142
This affects the chapter "Receive responses" of http://rethinkdb.com/docs/writing-drivers/ : 
In addition to `t`, `r`, `b` and `p` in the `Response` object, there can now be an additional field `n` containing the mentioned response notes array.
