### ISSUE TITLE
Make it clearer that you can only call `changes` after an indexed `orderBy`.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/docs#730]
See https://groups.google.com/forum/#!topic/rethinkdb/fdMKqf9Zaqc .

**Comment by mlucy** [comment]
Re-opening with slightly reduced scope: the docs say you have to use a secondary index, but you can use the primary index as well as a secondary index (so `.order_by(index: 'id')` works).  We should consider adding an example that uses the primary index too.

**Comment by chipotle** [comment]
Will that use case require the `(index:'id'`) form? And if so, does this actually mean that every command that either requires an index or gains improved performance from using an index can use primary indexes and secondary indexes interchangeably? Our documentation doesn't say that anywhere, as far as I know, and in some cases flatly contradicts it. (The docs for `order_by` explicitly say that indexes must have been created with `index_create`, for instance.)

**Comment by danielmewes** [comment]
@chipotle 
> Will that use case require the `(index:'id'`) form? And if so, does this actually mean that every command that either requires an index or gains improved performance from using an index can use primary indexes and secondary indexes interchangeably?

Yes and yes.
The name of the primary index will be the same as the name of the primary field. By default `id`, but could be different if the user specified a different `primary_key` during table creation.

**Comment by chipotle** [comment]
Okay. I'm going to open a separate issue for that, and leave this issue for fixing the wording specifically in the changefeed document. (I don't think there's any value in adding extra examples, though, if the syntax is literally identical -- you just have to clarify that `id` or another primary index can be used where secondary indexes can go.)

**Comment by hamiltop** [comment]
I'll also add that it isn't clear you can provide options for order_by. Correct me if I'm wrong but:

```
ORDER_BY   = 41; // Sequence, (!STRING | Ordering)... -> Sequence
```

should read:

```
ORDER_BY   = 41; // Sequence, (!STRING | Ordering)..., {index: !STRING} -> Sequence
```

**Comment by danielmewes** [comment]
@hamiltop you're right, I opened https://github.com/rethinkdb/rethinkdb/issues/4151 for that.
