### ISSUE TITLE
Document sorting order of ReQL types

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#734]
We've had many questions about how different ReQL types sort relative to each other, and also within one type.

For example it's not necessarily obvious that arrays sort lexicographically, and that `null` sorts between some other types (and not for example lower than all other types).

We should explain this somewhere.

**Comment by danielmewes** [comment]
Sorting order of objects is another non-obvious one (I don't know how they sort actually. @mlucy?)

**Comment by mglukhovsky** [comment]
The [data types](http://rethinkdb.com/docs/data-types/) document might be a good place to document this.

**Comment by mlucy** [comment]
@danielmewes -- `obj1 <=> obj2 == obj1.coerce_to('array') <=> obj2.coerce_to('array')`.  We order the fields lexicographically and compare one by one, considering the absence of a key to be smaller than any value for a key.

**Comment by chipotle** [comment]
So this explains how arrays elements are sorted and how object fields are sorted, but the other question is how types sort relative to one another -- if I have a sequence of [100, 200, "a", "b", [1, 2, 3], {"foo": "bar", "count": 999}, null], what happens?

**Comment by mlucy** [comment]
Values of different types sort in the same order as their type names.  (So if `x` and `y` are different types, `x <=> y == x.type_of() <=> y.type_of()`.)
