### ISSUE TITLE
Clarify the date and time modification section

### ISSUE THREAD

**Issue by Strikeskids** [rethinkdb/docs#736]
This clarification concerns this [section](https://github.com/rethinkdb/docs/blob/master/2-query-language/dates-and-times/python.md#modifying-times)

Here, both examples for subtracting two times or adding a number to a time produce a, as the output, a number. This could be confusing to the reader that misses the conversion `to_epoch_time()` in the first example and the lack of such a conversion in the second. Perhaps, using more recent times and not converting `to_epoch_time()` could assist in assuaging this confusion.

**Comment by danielmewes** [comment]
Good idea.
