### ISSUE TITLE
Clarify index usage

### ISSUE THREAD

**Issue by chipotle** [rethinkdb/docs#738]
Per comments in #730, commands like `orderBy` that take secondary indexes also take primary indexes, and this needs to be clarified in any commands where `id` isn't the default index.

**Comment by chipotle** [comment]
It doesn't look like there are any commands that require indexes that *don't* make `id` the default index, so this appears to be unnecessary. #730 turns out to be an unusual case relating to changefeed quirks.

**Comment by danielmewes** [comment]
What about commands that don't require an index but take one optionally, like the mentioned `orderBy`, `min`, `max` or `distinct` (well using the primary index with `distinct` isn't very useful, and I think we shouldn't mention it)?

**Comment by chipotle** [comment]
Hmm. I was thinking those wouldn't need extra clarification because indexes are optional, but it may be worth adding a parenthetical when it refers to the indexes.
