### ISSUE TITLE
distinct API docs: Add a note that applying it to a table without an index isn't useful

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#740]
http://rethinkdb.com/api/javascript/distinct/

We mention that
"The distinct command can be called on any sequence, a table, or called on a table with an index."
and the table case also appears as a special case in the type signature.

This is fine, but we should mention that calling `distinct` directly on a table without an index is a no-op. The way it is now it might appear like `distinct()` was doing something useful (like ignoring the primary key) when applied on a table.

Pinging @mlucy just to make sure I'm not forgetting anything here.

**Comment by mlucy** [comment]
`distinct` on a table isn't a no-op; it turns it from a table into a stream (so you can't do `table.distinct.get` for example).  But, yes, it doesn't change the content of the stream at all, and it isn't really useful; we just support it because we wanted `distinct` to be defined on all streams.

**Comment by danielmewes** [comment]
@mlucy thanks for clarifying.

**Comment by chipotle** [comment]
I think it might be best to remove the non-index case from the description and API signature, and then add an infobox explaining `table.distinct` without an index.

**Comment by danielmewes** [comment]
I'm not sure if it's a good idea to remove it from the signature. It's good to have the signatures complete (they're also helpful for external tools and driver developers who might use them for deducing the result types of terms).

Removing it from the description makes sense though, and adding an info box I think makes sense as well.

**Comment by chipotle** [comment]
I don't see that it needs two separate lines in the API signature, though; both lines say that a `table` input to `distinct` returns a `stream`. Generally, we only have separate lines in the signature block when either the input or output is different, right?

**Comment by danielmewes** [comment]
@chipotle You're absolutely right. Ignore my previous comment. We should just denote that the index option is optional then.
