### ISSUE TITLE
Link to official Docker image, add another user-contributed one

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#745]
On this page http://rethinkdb.com/docs/frameworks-and-libraries/ we currently link to http://dockerfile.github.io/#/rethinkdb as well as two other places for a dockerfile, but don't mention the official RethinkDB Docker image: https://registry.hub.docker.com/_/rethinkdb/

We should list the official one first I think, and community-supported ones below it, probably under the same bullet point for not making it too confusing. For example as "Alternative images: ... by @... , ... by @..., ... by @...".

User @grzesiek just created another dockerfile, that he says is more up to date than the dockerfile/rethinkdb one. It can be found at https://github.com/grzesiek/docker-rethinkdb . We should list that one too.

**Comment by grzesiek** [comment]
I couldn't find and didn't know about official image so I made new one. It its slightly different than official, so I may also come in handy.

:+1: for mentioning official one at rethinkdb.com, so others could find it
