### ISSUE TITLE
Add minval/maxval terms

### ISSUE THREAD

**Issue by chipotle** [rethinkdb/docs#746]
This is mostly so they appear in the Data Explorer and Python help strings, which was an issue surfaced in #731. (I think this is a separate issue from that one, though.) A couple questions, for @danielmewes and anyone else: do these work in any command other than `between`? And are there any other "special purpose constant" type terms we should add to the API?

**Comment by danielmewes** [comment]
@Tryneus will know for sure, but I think they only work in `between`.
Other terms of similar scope are `r.asc` and `r.desc` for `order_by`.

**Comment by Tryneus** [comment]
That is correct - `r.minval` and `r.maxval` are only useful for `between`, but we allow users to put them wherever they want in a query.  `r.asc` and `r.desc` are actually restricted to be the direct descendant of a `order_by` term (which has a few unfortunate side-effects, i.e. rethinkdb/rethinkdb#3188 and rethinkdb/rethinkdb#4143).

**Comment by chipotle** [comment]
Is there an output type I should list in the `{% apibody %}` block and the `io` YAML header? I think those are necessary for the building scripts (at least for the data explorer).

For `asc` and `desc` we just alias to `order_by`; I'm wondering if we might be better off doing the same for `minval`/`maxval` and `between`.

**Comment by danielmewes** [comment]
According to `r.minval.typeOf()`, the type of `r.minval` is MINVAL and the type of `r.maxval` is MAXVAL.

Can you explain a bit what it would mean to alias them to `between`? Would the Data Explorer basically show the documentation of `between` when typing `r.minval`?

**Comment by chipotle** [comment]
Yes, essentially. You're only typing `minval` and `maxval` in the context of `between` so that would presumably be all right, although if that changes we'd have to revisit this.

**Comment by danielmewes** [comment]
Ok, either option sounds fine to me. You should pick the one that's less work.

**Comment by mlucy** [comment]
`minval` and `maxval` are sometimes useful outside between (e.g. in `filter`), so I'd recommend giving them their own docs if it's easy.
