### ISSUE TITLE
TABLE_SLICE.between doesn't default to the primary key

### ISSUE THREAD

**Issue by neumino** [rethinkdb/docs#752]
These two queries are the same.
```
r.table('data').orderBy({index: 'foo'}).between(2, 3)
r.table('data').orderBy({index: 'foo'}).between(2, 3, {index: 'foo'})
```
And this will fail:
```
r.table('data').orderBy({index: 'foo'}).between(2, 3, {index: 'id'})
```

I can see where this behavior comes from, and I'm not sure if it's by design, but if it is, the docs should be updated.

**Comment by mlucy** [comment]
This was originally intentional, but looking at it now it seems really confusing.  I opened https://github.com/rethinkdb/rethinkdb/issues/4188 to discuss changing it.

**Comment by danielmewes** [comment]
Thanks for pointing this out @neumino . I wasn't aware that we were doing this.

@chipotle for the moment, the API documentation for `between` needs to be adapted slightly. http://www.rethinkdb.com/api/javascript/between/ It's currently saying "(it uses the primary key by default)", so there should be a note that it uses the index of a preceding `orderBy` instead if there is one.

**Comment by chipotle** [comment]
Just so I'm clear, from @neumino's example above, it looks like if you put `between` after `orderBy` then it will *always* use the index specified in `orderBy`, and trying to use another key wil
