### ISSUE TITLE
SQL->reql cheatsheet: add example of group by having count

### ISSUE THREAD

**Issue by rocketraman** [rethinkdb/docs#757]
An example of an SQL with a `group by` `having` `count(*) > x` would be useful. For example, in the movies database, if one wanted to find the duplicate movies (not distinct).

```
SELECT title,
       COUNT(title)
    FROM movies
    GROUP BY title
    HAVING COUNT(title) > 1
```

```
r.table('movies').withFields('title').group(r.row).count().ungroup()
 .filter(r.row('reduction').gt(1))
```

**Comment by danielmewes** [comment]
Thanks for the suggestion @rocketraman . That sounds useful, especially because it demonstrates the use of `ungroup()` which might not be obvious.

I think the query should be
```js
r.table('movies').group('title').count().ungroup()
 .filter(r.row('reduction').gt(1))
```
right?

**Comment by rocketraman** [comment]
@danielmewes Yes I think your query is simpler, and the result shape is closer to the shape of the SQL result. Cool!
