### ISSUE TITLE
Clarify sentence about time comparison

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#762]
@prgm noted in https://github.com/rethinkdb/rethinkdb/issues/4217#issuecomment-101419149 that this sentence from http://rethinkdb.com/docs/dates-and-times/ruby/ can be ambiguous:
> Times are considered equal if their seconds since epoch (UTC) are equal, ...

We could for example change that to say "Times are considered equal if the number of milliseconds since epoch (UTC) is equal"

**Comment by chipotle** [comment]
I'm going to merge this with #736, since they're both small changes to the same documents--which I'm working on at the moment--and it'll be easier to review them together.
