### ISSUE TITLE
Update the FAQ: split points can't be specified any longer

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#764]
Please correct me if I'm wrong on these details -- as I understand it, when we introduced the new admin API, we removed the ability to set split points manually, since it would have complicated the interface. We intend to move to consistent hash sharding, but in the interim, this statement in the [architecture FAQ](http://rethinkdb.com/docs/architecture/) is incorrect:

> In advanced situations, the user can specify the split points manually, and the system will partition the table into shards according to the user’s request. 

We should revise this to reflect the current state of affairs. Correct?

**Comment by danielmewes** [comment]
You are correct. We need to update the FAQ (pinging @chipotle).

**Comment by chipotle** [comment]
Actually, it looks like that paragraph should have been deleted in favor of
the (relatively new) paragraph immediately above it which ends "Users
cannot set shard points manually."
