### ISSUE TITLE
Clarify CAP theorem limitations

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/docs#766]
Overall I think you've done a great job on the architecture docs and explaining the trade-offs you made. However there was one section that I thought could be a little clearer.

> In RethinkDB data always remains immediately consistent and conflict-free, and a read that follows a write is always guaranteed to see the write.

While this is technically true, it would probably be more accurate to say something like:

> In RethinkDB data always remains immediately consistent and conflict-free, and a read that follows a write is always guaranteed to see the write (but neither the read nor write are guaranteed to succeed if the server is unavailable).

You talk about the failure scenarios further down, but as this is the first part of the CAP section, I think it would be helpful to give people a general understanding before continuing into the details. As it stands, without explicitly acknowledging the failure scenario (especially when discussing the CAP theorem), it seems like you're claiming that it is always immediately consistent and always available (which you're not, and the docs further down make that clear).

What are your thoughts?

**Comment by danielmewes** [comment]
That's a great improvement @danielcompton, I agree that your version is much clearer.

We might want to wait for our next release (which will come with auto failover) before updating this, since then we can make it even more accurate:
> In RethinkDB data always remains immediately consistent and conflict-free, and a read that follows a write is always guaranteed to see the write (but neither reads nor writes are guaranteed to succeed *if a majority of servers* is unavailable).

**Comment by danielcompton** [comment]
Sure, thats an even better thing to be able to tell people :smile:. Is that release 2.0.2?

**Comment by danielmewes** [comment]
@danielcompton I should have said next major release. It's going to be 2.1.0.

**Comment by danielmewes** [comment]
Something that came up on Slack:
The part about "a read that follows a write is always guaranteed to see the write" is slightly ambiguous, because this is only true if you wait for the write to be acknowledged.
I suggest we slightly change that part as well to say "a read that follows an *acknowledged* write is always guaranteed to see the write"

**Comment by chipotle** [comment]
"The server" is ambiguous; I'm presuming this means the primary replica (at least in the 2.0 model). I think we might want to shuffle the whole paragraph around a bit to introduce the notion of primary replicas first, if that's the case. So instead of:

> In RethinkDB data always remains immediately consistent and conflict-free, and a read that follows an acknowledged write is always guaranteed to see the write. This is accomplished by always assigning every shard to a single authoritative primary replica. All reads and writes to any key in a given shard always get routed to its respective primary where they're ordered and evaluated.

We can say:

> Every shard in RethinkDB is assigned to a single authoritative primary replica. All reads and writes to any key in a given shard always get routed to its respective primary, where they're ordered and evaluated. Data always remains immediately consistent and conflict-free, and a read that follows an acknowledged write is always guaranteed to see the write. However, neither reads nor writes are guaranteed to succeed if the primary replica is unavailable.

At least assuming I have this right. :) We can update this for 2.1 when it ships.

**Comment by danielmewes** [comment]
I like that new wording.
It will mostly still be correct with 2.1, though we might then want to clarify that the primary replica can change at any time due to auto failover.
