### ISSUE TITLE
Update documentation for indexWait

### ISSUE THREAD

**Issue by hamiltop** [rethinkdb/docs#767]
in https://github.com/rethinkdb/rethinkdb/blob/v2.0.1/src/rdb_protocol/ql2.proto#L536 it says that indexWait returns the same values as indexStatus, but the documentation (http://rethinkdb.com/api/javascript/index_wait/) says something different. The actual behavior is as stated in `ql2.proto`

**Comment by danielmewes** [comment]
Thanks for opening an issue @hamiltop .
Looks like the `function` and `geo` fields are the ones missing from the `index_wait` documentation?
