### ISSUE TITLE
Publishing the RethinkDB driver spec

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/docs#768]
I really like http://rethinkdb.com/docs/writing-drivers/ for understanding the overall process for building a driver, and have seen https://github.com/rethinkdb/rethinkdb/blob/next/src/rdb_protocol/ql2.proto. However I feel like there is a spot in the middle missing for a formal spec describing each version of the protocol. I'm particularly interested in understanding the differences between v03 and v04, and can't seem to find a comprehensive list of changes.

On the [RFC for the protocol](http://www.rethinkdb.com/blog/rethinkdb-wire-protocol-call-for-comments/), it looked like there was a wiki article with these details - https://github.com/rethinkdb/rethinkdb/wiki/protobuf_rfc_raw_spec, but the wiki seems to have been closed as that just redirects to rethinkdb/rethinkdb.

Are you able to help point me towards the right docs? It would be good to link to them from the writing drivers page as well.

**Comment by AtnNn** [comment]
We don't keep docs for older versions of the driver protocol. There are however plans to start keeping old docs around (#665).

You can find old versions of the driver spec using `git log`:

https://github.com/rethinkdb/docs/commits/master/1-get-started/drivers/writing-drivers.md
https://github.com/rethinkdb/docs/commits/master/1-get-started/drivers/driver_protocol.md

For a more authoritative reference, you can take a look at the messages and comments in `ql2.proto`. Use a version tag to get the information for a specific version, for example `git show v1.8.0:src/rdb_protocol/ql2.proto` for RethinkDB 1.8.0.

https://github.com/rethinkdb/rethinkdb/commits/master/src/rdb_protocol/ql2.proto

I believe that the protobuf_rfc_raw_spec page on the old wiki was simply an early version of `ql2.proto`.

**Comment by danielcompton** [comment]
Thanks @AtnNn, this is quite helpful for seeing the changes to the wire protocol. Is there anywhere described the differences in behaviour between v03 and v04?

> Note: All instructions below assume a protocol of V0_3 or higher.

from http://rethinkdb.com/docs/writing-drivers/ implies that unless otherwise stated V0_3 and V0_4 have the same connection behaviour.

> Starting with RethinkDB 2.0 (V0_4), the server will process multiple queries in parallel rather than sequentially, and there is no guarantee that a read following a write on the same connection will “see” the results of the write as long as it’s successful. 

Is there any more discussion on this behaviour, and are there any other changes to the behaviour of the spec between V0_3 and V0_4?

Looking at the 2.0.0 release notes I couldn't see any mention of the new protocol. It looks like this was discussed at https://groups.google.com/d/msg/rethinkdb-dev/3qxVOW05Y58/5hdYK7qSIOgJ. This is great, but not as discoverable as having a changelog in the repo for spec changes.

Really appreciate the work you guys do, thanks for your hard work.

**Comment by AtnNn** [comment]
The *rethinkdb-dev* post you link to describes all the differences introduced by RethinkDB 2.0 (aka V0_4).

Although the RethinkDB release notes do not mention the version V0_4 bump, it does mention all the changes to the protocol.

As you've discovered, the changes that affect drivers are posted to the mailing list, as described in the [writing-drivers](http://rethinkdb.com/docs/writing-drivers/) article:

> You can ask questions and get notes on changes introduced in new versions of RethinkDB on the [RethinkDB-Dev Google Group](https://groups.google.com/forum/?fromgroups#!forum/rethinkdb-dev)

Although it is not in the repo, it serves as a separate changelog for those changes. Perhaps we could make it easier to discover.

**Comment by danielmewes** [comment]
While I think this isn't critical, I agree that the dev mailing list is not easy enough to discover given how useful the driver release posts are for keeping a driver up to date.

@chipotle Do you think we could have a more prominent box closer to the top of http://rethinkdb.com/docs/writing-drivers/ to point to the mailing list? Something along the lines of "Join the RethinkDB-Dev Google Group to receive updates on protocol changes."?

**Comment by chipotle** [comment]
That seems reasonable.

**Comment by deontologician** [comment]
Could we post the per-release driver developer notes that @mlucy sends out on the site somewhere?

**Comment by mlucy** [comment]
Maybe not, they're in the form of patches from one version to the next and thus not all that useful as general documentation.  (Also, you can browse them in the google group.)
