### ISSUE TITLE
Error handling documentation

### ISSUE THREAD

**Issue by chipotle** [rethinkdb/docs#769]
We don't document the kinds of errors that RethinkDB drivers may throw -- as far as I know, the official drivers have a standard set such as `RqlDriverError`, `RqlCompileError`, etc. We should consider whether it's worth adding a separate page that documents these and gives some advice on how to handle them.

(This replaces #6, which is both old and poorly titled.)

**Comment by danielmewes** [comment]
That sounds like a good idea.
We should not invest too much time though before we haven't improved the error type hierarchy on the server and in the clients.

**Comment by chipotle** [comment]
I think #824 covers a sufficient amount of this to be considered a duplicate -- it adds a separate page on error types -- so I'm closing this one.
