### ISSUE TITLE
Writing Drivers page doesn't seem to be linked to from http://rethinkdb.com/docs

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/docs#774]
The [writing drivers](https://github.com/rethinkdb/docs/blob/master/1-get-started/drivers/writing-drivers.md) page doesn't seem to be linked from the main docs page. It is linked from [get-started/drivers/index](https://github.com/rethinkdb/docs/blob/4be78f6920d36e91d3e52da8554faaf0df486046/1-get-started/drivers/index.md), although I'm not sure how to get to that page following links on the website.

It would be good to have this as a sidebar option on the main docs page, perhaps under the "Get Started" section as it seems like it's meant to be linked to from there.

**Comment by chipotle** [comment]
This doesn't seem like a "Getting Started" kind of topic -- it's fairly advanced -- but it doesn't obviously fit into any of the other sections, either. "Getting Started" might be the best place to put it until we do a documentation reorganization.

**Comment by danielcompton** [comment]
I agree, it's fairly advanced, but it is located in the getting started folder so that's why I assumed it would go there.

**Comment by chipotle** [comment]
Closed in rethinkdb/www-thoughtbot#87
