### ISSUE TITLE
Reduce prominence of the Publish-subscribe article and repo

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/docs#776]
Not sure what the best way to do this would be, open to suggestions. https://github.com/rethinkdb/example-pubsub/issues/6#issuecomment-104342400 and other issues on the rethinkdb/example-pubsub repo indicate people are getting sucked in there when they are basically looking for how to use changefeeds. The goal of that repo is to show how changefeeds can be used in a similar way to topics in message queues, not as the main way people should be using changefeeds.

My suggestion is to add a disclaimer to the publish subscribe article and the repo README indicating that if they just want to subscribe to notifications on queries, they should check out the changefeeds article.

Given how small the use case is for this kind of library, it may make sense to unlink it from the website and deprecate the repo to ensure more people don't get ensnared by it. But that may be too drastic.

@mglukhovsky @coffeemug suggestions?

**Comment by deontologician** [comment]
For reference, the publish subscribe article is here: http://rethinkdb.com/docs/publish-subscribe/javascript/

**Comment by deontologician** [comment]
Another factor perhaps in favor of removing it is that at the time it was written, you could only subscribe to a table, not to filter queries etc. So it was providing a layer of convenience that is no longer really needed.

**Comment by mglukhovsky** [comment]
I think an infobox at the top saying to go check out the changefeeds article first would be wise. We're going to have _significantly_ more articles about libraries and tools (based on blog posts), so this belongs with that set.
