### ISSUE TITLE
Clarify order of precedence with which database is used given multiple database contexts

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/docs#782]
As far as I can tell, there are three possible database contexts that can be used in a query:

1. The `db` function which constructs a term
2. Specifying a default database on a connection
3. Specifying a database in the `run` function 

From my testing it seems that the precedence is as follows:

1. If a `db` term is present in a query then it is used always
2. If no `db` term is present then the default database in the connection is used
3. If there is no `db` term and no default database specified, then the db from the `run` function is used.

Is this a correct understanding? I think it would be good to document this precedence somewhere. In our case it's fairly important, as we're receiving queries from an untrusted client, and it'd be great to force db scope to only that client. 7However that doesn't seem to be possible without rewriting the query.

**Comment by mlucy** [comment]
@danielcompton -- that's accurate.  The global `db` optarg is only used if you write `r.table` instead of `r.db(...).table`.

In general I would strongly advise against running untrusted queries right now.  (After https://github.com/rethinkdb/rethinkdb/issues/218 or a similar issue gets in it will be a lot safer.)

**Comment by danielmewes** [comment]
I suggest that we add a note to the `db` API page http://rethinkdb.com/api/javascript/db/ about the alternative way of selecting a DB by setting the default DB during connection setup or through `use`.

I'm not sure if we mention the option of passing a db as a global optarg anywhere right now, and I'm undecided on whether we should include it in the documentation or not (though I suspect the answer is yes).
