### ISSUE TITLE
Improve init script docs (/docs/cluster-on-startup/)

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#79]
The `systemd` instructions have two problems:

- Preferably we should provide sample config files and copy them into place, rather than instructing the user to create files
- The sentence "Add the file `/usr/lib/tmpfiles.d/rethinkdb.conf` with the content:" is confusing. Instead, it should read:

> Create the file /usr/lib/tmpfiles.d/rethinkdb.conf with the following line:

**Comment by chipotle** [comment]
I think all of these have been addressed save for the primer/walkthrough idea, which we should revisit as part of the ontology update.
