### ISSUE TITLE
Website makes it seem as if new primaries are automatically elected after permanently removing a server

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/docs#792]
See https://github.com/rethinkdb/rethinkdb/issues/4406.

**Comment by chipotle** [comment]
If this is wrong, I need some more clarification about the current behavior; the paragraph being referenced about automatic election was written in January and passed code review.

**Comment by timmaxw** [comment]
Sorry, I guess I misinformed you. In 1.16 or 2.0, if a shard's primary is permanently removed, the shard will not have any primary until the user sets the primary with `reconfigure()` or by writing to `table_config`.

This might not be worth fixing because the behavior will change again in 2.1.

**Comment by danielmewes** [comment]
We'll keep the documentation for 2.0 around for a while, so I think it's worth fixing (should be a quick fix I imagine).
