### ISSUE TITLE
Limitations page should mention memory overhead proportional to disk data size

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/docs#806]
RethinkDB keeps some data structures in RAM that are proportional in size to the data on disk. I think it's about 1% depending on the details of the user's dataset. (@danielmewes has better numbers.) We should mention this on the limitations page.

Also, the `docs/architecture` page claims that "RethinkDB can operate on terabytes of data with only a few megabytes of cache space", which is wrong. We would need tens of gigabytes of RAM to operate on terabytes of disk data.

**Comment by chipotle** [comment]
I assume this is on every machine in the cluster (and it's distinct from the 8MB per table overhead already mentioned in the limitations document)?

**Comment by timmaxw** [comment]
It's proportional to the amount of data stored on disk on that particular machine. Yes, it's distinct from the 8MB per table overhead.

**Comment by danielmewes** [comment]
Good catch.

It's the thing we talk about here: http://rethinkdb.com/docs/memory-usage/
> RethinkDB organizes data into blocks. Blocks in RethinkDB are sized in steps of 512 bytes up to a maximum of 4 KB. While the content of a block itself can be cleared from main memory to free space, metadata of approximately 28 bytes per block (as of RethinkDB 1.13) is always kept in memory. Thus, this memory overhead is directly proportional to the number of blocks that a given data set requires.

In the worst case this overhead ends up in the range of 5% of the total data size (which is roughly equal to the on disk size without any secondary indexes). The specific value depends on the size of the individual documents, and both small (below 250 bytes) and large documents over 512 bytes are significantly more efficient than this.

**Comment by danielmewes** [comment]
1-5% is a reasonable ball-park estimate for this overhead.
