### ISSUE TITLE
Add `indexes` field to table_config documentation

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#812]
There will be an additional field which lists the names of secondary indexes in the `table_config` table per https://github.com/rethinkdb/rethinkdb/issues/4525 .

The format is probably going to be `indexes: ["idx1", "idx2", ...]` but let's wait until it's implemented before updating the docs to be sure.

**Comment by VeXocide** [comment]
The format is exactly as @danielmewes described it.

**Comment by chipotle** [comment]
If a table has no secondary indexes on it, is this field present with a value of `[]` or `null`, or is it not present at all?

**Comment by VeXocide** [comment]
The field will be present with a value of `[]`.
