### ISSUE TITLE
Tornado example code syntax problems

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#832]
At least on Python 2.7 and 3.4 on newton, I get a syntax error when trying this example from http://rethinkdb.com/docs/async-connections/#python-and-tornado
```python
@gen.coroutine
def single_row(connection):
    # Insert some data
    yield r.table('test').insert([{"id": 0}, {"id": 1}, {"id": 2}]).run(yield connection)
    # Print the first row in the table
    row = yield r.table('test').get(0).run(connection)
    print(row)
```

The fix seems to be to take out the `yield connection` and change the code to something like this:
```python
@gen.coroutine
def single_row(connection_future):
    # Wait for the connection to be ready
    connection = yield connection_future
    # Insert some data
    yield r.table('test').insert([{"id": 0}, {"id": 1}, {"id": 2}]).run(connection)
    # Print the first row in the table
    row = yield r.table('test').get(0).run(connection)
    print(row)
```

The other Tornado examples on the page have similar problems (they all use `yield connection` inside of `run`).

I'm not sure if this is something that changed in a certain version of Python, nor whether there is a different way to avoid this problem. @Tryneus do you have any insights into this?

**Comment by danielmewes** [comment]
A user on the Google group noticed this initially https://groups.google.com/forum/#!topic/rethinkdb/J4n13ytZOQM

**Comment by chipotle** [comment]
The examples I used were taken from the original writeup Graham did; I remember he changed the code substantially after the first draft, and I think added the `yield connection` then. I don't know if that was due to a change in Python or Tornado, though.

**Comment by Tryneus** [comment]
Yeah, this is a syntax that is not available in all versions of Python that we support, unfortunately.  If you use the return value of a yield statement, is has to be a direct assignment in most versions (if I remember correctly).  This is probably just an oversight due to some quick iterations when the API wasn't quite settled.
