### ISSUE TITLE
Documentation for Arrays as Primary Indices Is Lacking

### ISSUE THREAD

**Issue by weshoke** [rethinkdb/docs#840]
```
{
  id: [v1, v2, v3]
}
```

Primary indices with arrays isn't very well (or at all) documented.  I wasn't able to find anywhere that mentions it.  The document on secondary indices might apply, but the link to arrays for primary indices isn't made AFAICT.

The implications for the above for getAll, filter, between, etc. would be nice to see written up.

**Comment by chipotle** [comment]
The `tableCreate` documentation mentions the types allowed for primary keys, and mentions arrays as an allowed type; I'm not sure there's much else documentation, though. The `between` documentation talks about how compound indexes are treated, but it would be a good idea to clarify that "compound key" and "array key" are essentially the same thing.

With commands that don't rely on ReQL sorting order, I'm not sure there are any special implications -- I think values are just values: `r.table('foo').getAll('bar')` and `r.table('foo').getAll(['bar', 'baz'])` are both essentially "give me the document in table `foo` whose primary key matches this value." Are there special considerations for array indexes, @danielmewes ?

**Comment by danielmewes** [comment]
That sounds correct @chipotle, the interesting commands are the ones that rely on sorting order (primarily `between`, but also `orderBy`).

Mentioning the "compound key" = "array key" identity in `between` sounds like a good idea to me.

**Comment by danielmewes** [comment]
(... and also mentioning that this can be done with the primary index as well, not just with secondary indexes)

**Comment by chipotle** [comment]
`between` definitely talks about primary keys -- it defaults to `id`. It doesn't look like `orderBy` has a default for `index`, so it'd be a good idea to note there that you can use the primary key if you want to.

**Comment by ntquyen** [comment]
I wonder how the data sharding/partitioning is done when the primary key is of type array or different than string?
