### ISSUE TITLE
Full-text search docs promise more than we deliver

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#842]
http://rethinkdb.com/docs/elasticsearch/ is overly optimistic right now. It says things like
"For those applications that need full-text search, we’ve got you covered. We’ve written a plugin for Elasticsearch (called a river) that keeps RethinkDB synced up with Elasticsearch’s indexes" and doesn't make it obvious that our river plugin has very serious limitations right now.

I think there should be a big warning in the document. From the "Caveats" section of the river plugin README:
> Currently, there's no way to guarantee that no documents are lost if the river loses connection with the RethinkDB server. The only way to be sure is to backfill every time, and this will still miss deleted documents.

With RethinkDB 2.2 we will be able to guarantee that no documents are lost (thanks to `return_initial`), but it will still be required to backfill from scratch after every restart.

At the moment this solution only works for relatively small data sets (where backfilling/replicating into Elasticsearch from scratch is an option), and where it's ok to have some outdated data in the text index.

**Comment by ha1331** [comment]
Maybe also consider explaining what "server" means in this case. Is server the one syncing with elasticsearch, any primary of any table that is being synced with elasticsearch or both.

**Comment by AnneTheAgile** [comment]
@danielmewes , maybe you should submit a PR?

**Comment by AnneTheAgile** [comment]
@danielmewes, wait, I didn't realize you are on the core team. Maybe the wording of the issue should be you would like a PR?
