### ISSUE TITLE
Document new heartbeat setting on `cluster_config` admin table

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#847]
This was implemented in https://github.com/rethinkdb/rethinkdb/issues/4449.

The document looks as follows:
```js
 {
    "heartbeat_timeout_secs": 10 ,
    "id": "heartbeat"
} 
```

**Comment by VeXocide** [comment]
Sorry, I'd completely forgotten to create a docs issue for this. Note that it's a cluster setting, quite like the `auth` key.
