### ISSUE TITLE
I write a book about RethinkDB

### ISSUE THREAD

**Issue by kureikain** [rethinkdb/docs#849]
Hi all,

I love RethinkDB and contribute some of thing such as RethinkDB ORM http://github.com/kureikain/epiphy, RethinkDB and FluentD https://github.com/kureikain/fluent-plugin-rethink and Relang http://github.com/kureikain/relang

All that being said that I'm in love with it. One year ago, I started to document it because I want to learn more about it. At first, I blog, ot one point I started to writing it in markdown, using pandoc to convert it into PDF then I switched to Leanpub.

One year later. I almost finish with it. Here is the result http://github.com/kureikain/simplyrethink
I'm going to publish the book soon at http://leanpub.com/simplyrethinkdb next week.
The book is still WIP though.

It would be great if someone on RethinkDB team can help me to review it, or/and write a foreword for it. 
Let me know what you think.

**Comment by danielmewes** [comment]
Hi @kureikain, that's really awesome!

I took a really quick look and the contents and structure sound interesting and useful. I haven't gone very deep into the contents yet.

One thing I noticed is that the grammar and spelling can use some improvements. Do you know someone who could do a proof read with respect to these aspects?

**Comment by kureikain** [comment]
@danielmewes Thanks. Yes, my English is quite bad :)

I'm trying to find some reviewer, some friends here(with better English) to help me fix those grammars and spellings.

**Comment by dalanmiller** [comment]
Howdy @kureikain! I'd like to offer my services as a proofreader to iron out some of the grammatical parts of your book. Would you mind emailing me at dalanmiller@rethinkdb.com and let me know how I can get the source files for editing? Or do you have all the material in a repo somewhere?

**Comment by danielmewes** [comment]
Going to close the issue, since it's not directly related to our documentation.

**Comment by danielmewes** [comment]
@kureikain Are you still working on the book? It's shown as 99% complete on Leanpub. Do you still need help with anything?
