### ISSUE TITLE
Syntax highlighting issues on `r.http` documentation

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#851]
I noticed some syntax highlighting issues throughout the documentation for [`r.http`](http://www.rethinkdb.com/api/ruby/http/) -- namely:

  - The `rb` language snippet is visible here:

![screen shot 2015-08-10 at 12 27 00 pm](https://cloud.githubusercontent.com/assets/91193/9188104/44b3f6a8-3f8d-11e5-8c16-c09e525362b2.png)

  - Some of the language snippets are one-line, rather than multi-line comments.

**Comment by chipotle** [comment]
Kramdown seems to have problems dealing with indented code in bullet lists. I think the `http` command could benefit from some reorganization, though, to bring its style more in line with the way we handle other commands, so I've been working on that.
