### ISSUE TITLE
Huge variety in specifying functions in method signatures

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/docs#854]
Here's the results of my survey of the docs. This is how the docs specify that a term accepts a function in the signature spec at the top:

Term | says it accepts a function with
----------------|------------------------------------------------
`eq_join`, `do` | `function`
`filter`, `inner_join`, `outer_join`, `offsets_of` | `predicate`
`map`, `concatMap` | `mapping_function`
`update`, `replace` | `object | expr`
`merge` | `object | function`
`contains` | `value | predicate`
`count` | `value_or_predicate`
`reduce` | `reduction_function`
`for_each` | `write_query`
`group`, `min`, `max`, `sum` | `field_or_function`
`order_by` | no mention it accepts a function in the spec, only in examples
`http` | no mention in spec, `page` optarg accepts function

I suggest we use the following specs:

Term | calls it:
----------------|------------------------------------------------
`update`, `replace`, `merge`, `group`, `min`, `max`, `sum`, `order_by`, `concatMap` | `function/1`
`for_each` | `write_function/1`
`filter`, `eq_join`, `inner_join`, `outer_join`, `offsets_of`, `contains`, `count` | `predicate_function/1`
`do`, `map` | `function/1+`
`reduce` | `function/2`
`http` | should specify `function/1` in the `page` optarg description

I'm going with erlang-style arity declarations since that seems about right for a dynamic language. It would become too verbose I think doing full type declarations for the functions (`predicate_function` and `write_function` are a nod in this direction without getting too far into the weeds). 

@mlucy @danielmewes thoughts?

**Comment by chipotle** [comment]
While I like the simplification, I'm not sure I like the Erlang arity bit; it's a fairly unusual notation we'd need to explain, and nearly all of our cases only take one argument. I'd consider just going with `function`, `write_function` and `predicate_function`, and specifically say "one or more arguments" or "two arguments" in text when necessary.

**Comment by deontologician** [comment]
That seems fine too
