### ISSUE TITLE
Dedicated section explaining query parallelization

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/docs#861]
Currently this information is scattered among various issues. For advanced querying, the documentation should explain:

- What is parallelized through shards and cpu cores
- What will be(issue links)
- Workarounds for what isn't(like limit, sample, distinct without index, cases where rethinkdb doesn't support the same index reused between multiple terms)
- If a unparallelizable term inside a subquery or in the beginning of a query "taints" the whole query performance

**Comment by danielmewes** [comment]
This is a great idea. We should definitely have documentation on that, as it sometimes causes unexpected changes in query performance.
