### ISSUE TITLE
Docs don't mention comparison operators are variadic

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/docs#864]
`eq`, `ne`, `le`, `lt`, `gt`, `ge` can be used like:

```
r.eq(1,2,1,2) # false
r.ne(1,2,3,4) # true
r.gt(5,4,3,2,1) # true
r.lt(1,2,3,1) # false
```

But the signatures don't mention it and there are no examples on those pages. The pages should probably mention that it uses the python-like convention of chaining them so `r.gt(1,2,3)` is equivalent to `r.gt(1,2).and(r.gt(2,3))` etc

**Comment by danielmewes** [comment]
I didn't know this worked. That's crazy.
