### ISSUE TITLE
the api sidebar disappears on the "uuid" javascript page

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/docs#867]
just this one page as far as I can see.

On a related note, the syntax highlighting seems weird on all three "uuid" pages. It's highlighting the uuid in the example strangely.

**Comment by danielmewes** [comment]
@mglukhovsky or @chipotle any ideas about the sidebar issue?

**Comment by danielmewes** [comment]
It also only seems to happen for the JavaScript version by the way. Python and Ruby seem to have the sidebar.

**Comment by chipotle** [comment]
Yep, it appears to be a case issue. "language: JavaScript" works;
"language: Javascript" makes the sidebar go away.
