### ISSUE TITLE
Table/shard limit

### ISSUE THREAD

**Issue by freiksenet** [rethinkdb/docs#873]
Hello!

In the 'limitations of RethinkDB' in FAQ there is:

> There is no hard limit on the number of tables per database or cluster. However, performance degrades based on the total number of shards across all tables on a cluster. The current recommendation is to keep this number below 300 (i.e., 300 tables with one shard each, or 50 tables with six shards each).

Does it mean that I shouldn't have more than 300 tables on one database server or is it somehow counted differently? I've tried googling, but the only reference to it is from long time ago and mentions that it might be fixed. What the current status of this limitation?

Thanks,

**Comment by danielmewes** [comment]
Thanks for bringing this up @freiksenet.
This used to apply on the cluster level, since having a lot of tables/shards made meta operations (such as reconfiguring a table) slow. This limitation should no longer exist in RethinkDB 2.1, but I'm going to double check.

**Comment by freiksenet** [comment]
That's great news! 


Thank you!

**Comment by danielmewes** [comment]
Just tested this on a 2 server cluster with 1,000 tables and 32 shards * 2 replicas each. The web UI and some queries to the `r.db('rethinkdb')` database become somewhat sluggish, but general meta operation performance seems to be fine.

@chipotle I think we can remove that point from the limitations.

**Comment by danielmewes** [comment]
@freiksenet Also server shutdown and startup can become somewhat slow with a lot of tables. Just something to keep in mind.
