### ISSUE TITLE
Document ReQL Values() term

### ISSUE THREAD

**Issue by encryptio** [rethinkdb/docs#875]
Values() was added in rethinkdb/rethinkdb#2945, with similar semantics to `.keys()`. It iterates over an object and returns the values, in the same order as `keys` does.

**Comment by encryptio** [comment]
The docs in 8473ac2f4b387003df48b6dc3f53ff9ac2f34d28 are a little misleading; the object `{ id: 1, name: "fred", email: "fred@example.com" }` would be ordered as `{ email: "fred@example.com", id: 1, name: "fred" }` in the database (asciibetically by key.)

That makes `keys()` return the order `["email", "id", "name"]` and `values()` return the order `["fred@example.com, 1, "fred"]`.

Perhaps replacing `email` with another field that starts after "i" would make the object nicer to read (because having the `id` in the middle feels weird)

**Comment by chipotle** [comment]
I've shuffled the various examples for `keys` and `values` to reflect `[ "id", "mail", "name" ]`.
