### ISSUE TITLE
JavaScript r.connect `ssl` option is documented incorrectly

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#879]
http://rethinkdb.com/api/javascript/connect/

The `caCert` option changed before the release. It is actually broken completely in the driver we shipped with 2.1, but once we have that issue fixed, it's going to work as follows:
* instead of `caCerts`, the option is called `ca`
* the `ca` option takes an array of strings of `Buffer`s containing certificates in the PEM format. In contrast to the other drivers, the certificate is not automatically loaded from a file but must be loaded manually.

The full set of options that can be passed into the `ssl` dictionary are listed here: https://nodejs.org/api/tls.html#tls_tls_connect_options_callback
We actually just pass them through to `tls.connect`.

An example of how the `ca` option can be used is in this PR by @pauliusuza https://github.com/rethinkdb/rethinkdb/pull/4786#issue-104478657

**Comment by chipotle** [comment]
Is this only true for the JavaScript driver, and the other languages still use 'ca_certs' as a path to a certificate?
