### ISSUE TITLE
Docs for tableCreate don't mention `r.tableCreate` form in signature

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/docs#880]

**Comment by deontologician** [comment]
I kinda think the `r.tableCreate` form is gross since it defaults to the test database, which is surprising

**Comment by chipotle** [comment]
While it's probably good to mention this exists, I'm not sure whether it's necessary to put it in the signature. As you mentioned, the chances are it's not going to come up very often in practice unless users are intentionally adding to the `test` database. Maybe just mention it in the body?

**Comment by mlucy** [comment]
I think if it's a legal way of using the term we should list it in the signature.  (Separate from that, I personally use `r.table_create` a lot.  I think it's pretty common to want to quickly create a table for testing when you're using RethinkDB interactively.)
