### ISSUE TITLE
Driver developer "gotchas"

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/docs#881]
These should probably be added to the driver developer document somewhere.

- The arguments to `r.do` are flipped around. The wire format requires that the function come first, and the arguments come last. So `r.do(1,2,3, (x,y,z) -> x+y+z)` turns into `r.do((x,y,z)-> x+y+z, 1,2,3)` when serialized.
- The `db` global optarg needs to be wrapped in a `DB` object when serialized, unlike any other optarg. The js driver opts to accept a string and wraps it automatically for you (see rethinkdb/rethinkdb#2495)
- `r.binary` has two possible serializations:
   - the normal `[BINARY [arg]]` serialization if arg is a ReQL term (not including a datum)
   - a special pseudotype serialization `{"$reql_type$": "BINARY", "data": <base64 encoded data>}`
   - The second one is used if the language's native binary format is passed in (`byte[]` in java, `bytes` in python etc)

If I think of other stuff or run across it, I'll add it in comments below

**Comment by danielcompton** [comment]
`r.row` is a helper method, not a native RethinkDB term.

**Comment by deontologician** [comment]
Isn't `r.row` `IMPLICIT_VAR`?

**Comment by deontologician** [comment]
But yeah, you have to do a bunch of special handling for it, it can't just be used straight like other terms

**Comment by danielcompton** [comment]
Yeah, that's what I meant :)

**Comment by chipotle** [comment]
There's an "Implicit variables" section in the existing driver documentation which talks about `IMPLICIT_VAR` and how to wrap the `r.row(x)` argument -- if there's more that should be added there specifically, let me know.

**Comment by chipotle** [comment]
Also, I think I might need a little clarification with the bit about the `db` global optarg. This can only be specified in `db`, `run` and `connect`, right? And `connect` and `run` aren't commands that get serialized. If you specify `r.table('users').run(db='blog')` does that get serialized as if it was `r.db('blog').table('users')`?

**Comment by mlucy** [comment]
@chipotle -- if you type `.run(db='blog')` it gets sent to the server as a global optarg, the query isn't rewritten.

**Comment by deontologician** [comment]
The global optargs get sent to the server pretty much the way they're specified (as a json object at the protocol level) except that the value of the `db` key can't just be a string specifying the name of the db to use, it has to be a serialized db object, so `{db: "foo"}` gets automatically translated by the js/py drivers into `{db: [14 ["foo"]]}`.
