### ISSUE TITLE
Add docs on how to do a two-phase commit

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/docs#887]
I think this would be useful for people (I just pointed someone on StackOverflow to http://docs.mongodb.org/master/tutorial/perform-two-phase-commits/ but it would be better to have our own).

**Comment by danielmewes** [comment]
The discussion and code in https://github.com/rethinkdb/rethinkdb/issues/1863 might also be relevant.

**Comment by chipotle** [comment]
This is essentially #598, complete with the same links, I think.
