### ISSUE TITLE
Missing braces on SQL to ReQL cheat sheet

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#896]
Noted by a user via email on these two documents:

  - https://www.rethinkdb.com/docs/sql-to-reql/python/
  - https://www.rethinkdb.com/docs/sql-to-reql/javascript/

This line is missing a matching brace:

![screen shot 2015-09-14 at 12 59 22 pm](https://cloud.githubusercontent.com/assets/91193/9860464/2ad5477c-5ae1-11e5-9a1b-7b2a5e536e6f.png)

**Comment by chipotle** [comment]
Actually, it turns out that the problem isn't a missing brace, it's an extra brace! The "}" shouldn't be there.
