### ISSUE TITLE
Confusing explanation of orderBy with secondary indexes

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/docs#900]
I was reading the docs for [secondary indexes](http://rethinkdb.com/docs/secondary-indexes/javascript/) and didn't understand this sentence. Is there a different way of expressing this idea?

> Currently, you cannot chain an orderBy using a secondary index after a getAll but only after a table.

**Comment by chipotle** [comment]
How about this as a rewrite for that section?

> An `orderBy` command that uses a secondary index cannot be chained after `getAll`. You can only chain it after a `table` command. However, you can chain `orderBy` after a `between` command provided it uses the same index.

**Comment by danielcompton** [comment]
That's a lot better!
