### ISSUE TITLE
swap reheat for js-data + js-data-rethinkdb

### ISSUE THREAD

**Issue by jmdobry** [rethinkdb/docs#902]
I no longer maintain [reheat](https://github.com/jmdobry/reheat), but my [js-data-rethinkdb](https://github.com/js-data/js-data-rethinkdb) is maintained and well-supported, therefore I suggest the docs be updated accordingly.

Can you please change

```markdown
- [reheat](https://github.com/jmdobry/reheat) by [@jmdobry](https://github.com/jmdobry)  
  JavaScript ORM for RethinkDB with promises.
```

to this

```markdown
- [js-data-rethinkdb](https://github.com/js-data/js-data-rethinkdb) by [@jmdobry](https://github.com/jmdobry)  
  A RethinkDB adapter for [js-data](https://github.com/js-data/js-data), a database-agnostic ORM for Node.js and the Browser.
```

I'd submit a PR, but this is much faster than going through my company's OSS patching process. Thanks!

**Comment by danielmewes** [comment]
Thanks for the update @jmdobry .

@chipotle could you put that in please?

**Comment by chipotle** [comment]
I'll make the change later this week. Thanks for the update!
