### ISSUE TITLE
"primaryKey" should be "primary_key"?

### ISSUE THREAD

**Issue by rundowncreator** [rethinkdb/docs#905]
Shouldn't "primaryKey" should be "primary_key" [here](https://rethinkdb.com/api/javascript/table_create/)?

> r.db('test').tableCreate('dc_universe', {primaryKey: 'name'}).run(conn, callback);

**Comment by chipotle** [comment]
In JavaScript, you give options in camelCase, rather than snake_case, so `primaryKey` is correct.

(In practice, you can usually use snake_case, too, so `primary_key` also works. I'm not 100% sure that will work in all cases, though.)

**Comment by rundowncreator** [comment]
Oh... I didn't realize the config options varied based on the language.  I'm using RethinkDB with PHP.  I'll switch to the Python docs.  Those seem to match up.

**Comment by chipotle** [comment]
The PHP port has its own API docs: http://danielmewes.dnsalias.net/%7Edaniel/php-rql-api/ -- that might be the most helpful, although our "official" docs go into more detail with examples.

It looks like it may be kind of like JS in that it'll accept both snake_case and camelCase. (I believe all the commands sent to the server are actually snake_case, and the language-specific client drivers do translation if the language convention is for camelCase methods.)

**Comment by rundowncreator** [comment]
Yeah, I rely heavily on the official docs, as they're more complete.

Thanks for your help!

**Comment by danielmewes** [comment]
Just a quick clarification: The PHP driver currently only accepts the snake_case variant of the parameters. It would probably make sense to add translation of camelCase options to it, but it doesn't currently exist.

**Comment by rundowncreator** [comment]
Thanks!
