### ISSUE TITLE
Api page for "default" mentions it can take a function, but doesn't have a signature or example

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/docs#906]
I never knew it could take a function. Apparently the docs mention it, but only in passing

**Comment by mlucy** [comment]
The function form isn't particularly useful since `default` only catches non-existence errors (the original spec was more ambitions), but basically you can put whatever code you want in there, and if the function accepts an argument then we pass it the string text of the error message:

```rb
irb(main):7500:0> r(1).add(nil).default{|err| err}.run
"Expected type NUMBER but found NULL."
```

**Comment by chipotle** [comment]
Is there a use case for this in its function form?

**Comment by mlucy** [comment]
The only real use case is changing the default value based on the error message.
