### ISSUE TITLE
Between docs signature doesn't mention chaining after orderBy

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/docs#907]
The signature and examples only mention being called on a table, but stuff like this is valid:

```js
r.table('foo').orderBy({index: "id"}).between(r.minval, r.maxval)
```

@mlucy I'm assuming this words because the indexed orderBy returns a selection, is it true `between` will work on all selections?

**Comment by deontologician** [comment]
Ah, ok I just noticed this note at the bottom:

> Note: If you chain between after order_by, the between command must use the index specified in order_by, and will default to that index. Trying to specify another index will result in a ReqlRuntimeError.

So it looks like this is a special case just for orderBy. In that case I think we should have at least one example, and the signature should reflect this fact

**Comment by chipotle** [comment]
How should we reflect this in a signature? `between` doesn't work on selections:

```
r.table('players').filter({course_handicap: 4}).between(100,102)

e: Expected type TABLE_SLICE but found SELECTION:
SELECTION ON table(players) in:
r.table("players").filter({course_handicap: 4}).between(100, 102)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                  
```

(I've never even heard of `TABLE_SLICE` before, and it's not documented anywhere.)

**Comment by mlucy** [comment]
The hierarchy is basically that a TABLE can degrade to a TABLE_SLICE which can degrade to a SELECTION.  `between` and `order_by` both take and produce a `TABLE_SLICE`.  Then there are some additional checks that you don't try to use two indexes, get two ranges at once, etc. etc.

**Comment by chipotle** [comment]
Okay, if we're going to add this to the signature for `between` the only way to do it is to show it taking table_slice, which means that we're going to have document table_slice as a RethinkDB-specific data type which (if I understand it correctly) behaves like a selection to every command that expects a selection. `between` can take either a table or a table slice but nothing else. Is it worth editing the API signature for `between` and `order_by` to reflect that they do *not* return "selection" but actually return "table_slice"?

**Comment by mlucy** [comment]
> Is it worth editing the API signature for between and order_by to reflect that they do not return "selection" but actually return "table_slice"?

Probably; otherwise it isn't obvious you can chain them after each other.
