### ISSUE TITLE
Missing the ruby replace doc

### ISSUE THREAD

**Issue by kureikain** [rethinkdb/docs#910]
I got 404 when access Ruby `replace` doc:

![screen shot 2015-10-08 at 10 30 39 am](https://cloud.githubusercontent.com/assets/49754/10374365/ae81679e-6da7-11e5-9af2-9e2dbb87ac9c.png)

It works for JavaScript and Python however. Not sure if it's only me. I tried to `curl` it from an AWS host an got 404 too:

```
curl -v http://www.rethinkdb.com/api/ruby/replace/ > /dev/null
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 72.14.189.19...
* Connected to www.rethinkdb.com (72.14.189.19) port 80 (#0)
> GET /api/ruby/replace/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.rethinkdb.com
> Accept: */*
>
< HTTP/1.1 404 Not Found
* Server nginx/1.2.7 is not blacklisted
< Server: nginx/1.2.7
< Date: Thu, 08 Oct 2015 17:31:47 GMT
< Content-Type: text/html
< Content-Length: 7701
< Connection: keep-alive
<
{ [data not shown]
100  7701  100  7701    0     0   101k      0 --:--:-- --:--:-- --:--:--  101k
* Connection #0 to host www.rethinkdb.com left intact
```

**Comment by danielmewes** [comment]
Pinging @chipotle 
Looking at https://raw.githubusercontent.com/rethinkdb/docs/master/api/ruby/writing-data/replace.md there is an extra backtick at the beginning of the file. Could that be causing issues?

**Comment by chipotle** [comment]
Yep, that fixes it. I'll commit a backtick-free version of the file and push a new version of the site in a few minutes.
