### ISSUE TITLE
API: sidebar links scroll you back to the top of the page

### ISSUE THREAD

**Issue by marshall007** [rethinkdb/docs#915]
**Steps to reproduce:**

1. View API docs for any term (ex. [`r.row`](http://rethinkdb.com/api/javascript/row/)).
1. Scroll down.
1. Click to expand any sidebar header and you are scrolled to the top.

**Comment by chipotle** [comment]
This is actually (I think) a bug in a script in the private WWW repository. I'm leaving this bug open so we can report if/when it's fixed, and because there's a non-zero chance we'll need to make a matching fix in here for the standalone docs site build.

**Comment by mglukhovsky** [comment]
@marshall007, thanks for reporting -- this exposed several other lurking bugs. Should be fixed now (and a "back to top" link now appears on all API docs for terms).

**Comment by marshall007** [comment]
@mglukhovsky no problem, thanks!
