### ISSUE TITLE
Document steps needed when migrating from pre 1.14 RethinkDB

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#922]
http://www.rethinkdb.com/docs/migration/ says:
> Starting with version 1.13 of RethinkDB, manual migration of data when upgrading between major versions (1.x → 1.y) is no longer necessary. 

However we dropped support for directly upgrading from RethinkDB 1.13 to RethinkDB 2.1.x. In that case, users first need to migrate to RethinkDB 2.0.5, rebuild all of their secondary indexes, and then in a second step migrate to RethinkDB 2.1.x.

We should document these steps.
This came up in a Google Groups question here: https://groups.google.com/forum/#!topic/rethinkdb/xLi_EmSdYBI

For 1.14 and onwards, the upgrade is still fully automatic as of RethinkDB 2.1, though RethinkDB 2.2 will no longer support direct upgrades from 1.14 and 1.15 anymore.

**Comment by chipotle** [comment]
So for upgrading from 1.8–1.12, you'll need to follow the "migrating old data" directions we already have -- those should let you migrate directly from those versions up to 2.1, right?

And we still have a link to the [deprecated migration script](https://github.com/rethinkdb/rethinkdb/tree/02b4f29e1e7f15b3edffcb68bf015578ec5783ab/scripts/migration) for version 1.7 or earlier. Does that require you to upgrade to an earlier version and then upgrade from there, or can it work to upgrade directly to 2.1?

**Comment by danielmewes** [comment]
> So for upgrading from 1.8–1.12, you'll need to follow the "migrating old data" directions we already have -- those should let you migrate directly from those versions up to 2.1, right?

This is correct as far as I can tell.

The deprecated migration script should also allow for directly upgrading to 2.1 from even older versions, though I wouldn't bet that it still works.
