### ISSUE TITLE
API docs for `r.union` should include changefeeds

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/docs#923]
The `r.union` command supports joining multiple feeds, but the API docs for `union` don't cover that at all. They should cover this and include examples.

/cc @chipotle

**Comment by mglukhovsky** [comment]
Just ran into this, because a user wanted to union changes from all of the tables in RethinkDB.

We should also add a mention of this to the [changefeeds article](https://rethinkdb.com/docs/changefeeds/javascript/) and [API docs for `.changes`](https://www.rethinkdb.com/api/javascript/changes/).

**Comment by chipotle** [comment]
I'd suggest that "How do I produce a changefeed with a union of two or more tables?" is a cookbook recipe. Adding an example to `union` is also a good idea; we should add more examples that use changefeeds to commands like this. (I don't know if I'd advocate adding an example to `changes()`, though.)

Maybe the language in the changefeed article needs to be strengthened to emphasize the "nearly any query can become a changefeed" aspect of the `.changes()` command. I'm a little leery of adding a section that calls out specific queries, unless we just have a quick list of examples -- but that might be better served by collecting a few more changefeed cookbook entries and linking to the cookbook from the changefeed article.
