### ISSUE TITLE
Some geospatial commands are missing .run(conn)

### ISSUE THREAD

**Issue by chipotle** [rethinkdb/docs#927]
Many of the commands give examples such as this one for `polygon_sub` in Python:

```py
outer_polygon = r.polygon(
    [-122.4,37.7],
    [-122.4,37.3],
    [-121.8,37.3],
    [-121.8,37.7]
)
inner_polygon = r.polygon(
    [-122.3,37.4],
    [-122.3,37.6],
    [-122.0,37.6],
    [-122.0,37.4]
)
outer_polygon.polygon_sub(inner_polygon).run(conn)
```

Defining the two polygons separately is clearer, but this won't actually work. Either the first two calls to `polygon` need to have `.run(conn)` added to  them, or the examples need to be rewritten so they're all one query. I'm not sure that `var outerPolygon = r.polygon(...)` can even be made to work in JavaScript without a bit of a hula dance, either, since the results are actually being returned to callbacks rather than variables.

**Comment by danielmewes** [comment]
Hmm I would actually expect this to work. When you assign `r.polygon(...)` to a variable, that just creates a query object. I think this should be fine?

**Comment by chipotle** [comment]
Hm. It looks like it does in Python, you're right. I'm not sure what the proper type declaration would be in Java; I'll have to check it with Josh.

**Comment by danielmewes** [comment]
I think it will be a `ReqlAst` object, but you might want to double-check with Josh that that works in this context.
