### ISSUE TITLE
Document the new `and`/`or` edge cases

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/docs#944]
We changed two edge cases in https://github.com/rethinkdb/rethinkdb/issues/4132 and https://github.com/rethinkdb/rethinkdb/issues/4696 .  `r.and()` and `r.or()` (with 0 arguments) are now legal and defined to be `true` and `false` respectively.  We also now define `r(false).or(nil)` to be `nil`.

**Comment by danielmewes** [comment]
This is partially addressed by https://github.com/rethinkdb/docs/pull/934 (though I just noticed that the signature still needs updating).

**Comment by chipotle** [comment]
#934 actually only updates the indexes, and I don't think we need to mention this in the index file because it *is* an edge case -- I want to mention it as a separate note in the main files for `and` and `or`. (Although an update to the signature will go in the index files too.)
