### ISSUE TITLE
Systemd instructions in start on startup doc are confusing for Ubuntu users

### ISSUE THREAD

**Issue by segphault** [rethinkdb/docs#951]
When a user installs RethinkDB from our official Ubuntu package, the installation process displays the following message: "The RethinkDB startup service is installed but disabled. To enable it,
follow the instructions in the guide located at http://www.rethinkdb.com/docs/guides/startup/"

When the user clicks through the link and arrives at that page, it's not obvious what steps they should follow for Ubuntu. Because Ubuntu has recently adopted systemd, there's now some ambiguity about whether Ubuntu users should follow the steps in the "Startup with systemd" section. As far as I can tell, those steps are still unnecessary on Ubuntu and don't actually work in that environment. I think it would be helpful to clarify this so that it's easier for users to understand which instructions are applicable.

(Thanks to @unculture for bringing this issue to our attention.)

**Comment by danielmewes** [comment]
Maybe we could add small icons to the sections that represent the major distributions for which the instructions apply? Probably for all the distributions that we list here http://rethinkdb.com/docs/install/ ?

Additionally, Ubuntu seems important enough to add an explicit warning box to the `systemd` section follow the `init.d` instructions instead on Ubuntu.

**Comment by chipotle** [comment]
Closed in 34df2de5a071168033146591489faf552f1115aa
