### ISSUE TITLE
delete_at, insert_at, splice_at, change_at, and slice use the word "index", possibly confusingly

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/docs#955]
It's possible we should change the argument names in these api pages along these lines:

* `index` -> `offset`
* `startIndex` -> `startOffset`
* `endIndex` -> `endOffset`

It's also possible this might not be super confusing, but reading sentences like 

```
If only `index` is specified, `deleteAt` removes the element at that index.
```

are somewhat ambiguous as to whether we're talking about a table index or the array index.

**Comment by chipotle** [comment]
I'm not entirely convinced this is a problem -- these commands only operate on arrays, and "remove the element at that index" only makes sense if you're talking about an array index, AFAICT -- but I'm not against making the change.

**Comment by deontologician** [comment]
It's kind of a gray area, I could go either way but figured it was worth discussing

**Comment by danielmewes** [comment]
I think the sentences are ok, but I think changing the argument names in the API signatures is a good idea.
When scanning over the API signatures in the API index, users might not immediately realize that these commands are about arrays, rather than secondary indexes.
