### ISSUE TITLE
https://rethinkdb.com/docs/changefeeds is out of date

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/docs#965]
It doesn't reflect the changes from https://github.com/rethinkdb/docs/issues/920 .  In particular:

* It doesn't mention `include_initial` anywhere.
* It states that point changefeeds and `.orderBy.limit` changefeeds return initial values by default, which is no longer true.

**Comment by mglukhovsky** [comment]
@chipotle: I reopened this issue, because the Java docs for changefeeds are based on the older JavaScript article, and don't include these changes.

**Comment by chipotle** [comment]
This document is included in the #971 checklist -- the document hasn't been updated for Java at all yet. I'm reclosing this ticket, but adding a note over there.
