### ISSUE TITLE
https://www.rethinkdb.com/docs/async-connections/ needs `on_uninitial_val` added to the EventMachine documentation

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/docs#967]
There's already documentation for `on_initial_val`, `on_uninitial_val` is analagous.

(The documentation for `on_initial_val` is also slightly out of date because it implies that `.get.changes` and `.order_by.limit.changes` return initial values by default, which is no longer true ("if the changefeed returns initial values (such as .get.changes or .order_by.limit.changes), those initial values will be passed to this method.").  We should probably fix that at the same time.)

**Comment by chipotle** [comment]
I'll work on this after #970.
