### ISSUE TITLE
Consider adding docs somewhere for how to fix the  "cannot use r.row in nested queries" error

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/docs#973]
It would be nice if when people get that error message, they could google and find a page that shows them how to rewrite a query using `r.row` to one using a function.  Right now if you google that you just get a bunch of discussions on GitHub.

**Comment by mglukhovsky** [comment]
Agreed! :+1:

**Comment by samkelleher** [comment]
Google led me to this exact GitHub discussion 🔎

Still looking for a solution, but yeh I guess as someone who's been only using RethinkDB for a couple of weeks some orientation for things like this is very welcome.

**Comment by mlucy** [comment]
@samkelleher -- if you replace `.filter(...r.row...)` with `.filter(function(row) { return ...row...; })` that should fix it.

**Comment by chipotle** [comment]
This is actually documented in the `row` command API docs already, but I think it could be highlighted better than it is. I'll shuffle things around a bit as well as adding something to the troubleshooting docs.
