### ISSUE TITLE
Use Go Gopher as the logo for Go

### ISSUE THREAD

**Issue by encryptio** [rethinkdb/docs#981]
In [the client driver page](https://rethinkdb.com/docs/install-drivers/) we use a generic "text in a box" logo for the Go community driver, which sticks out like a sore thumb to someone that regularly uses Go.

The Go Gopher is the mascot of Go, and is the closest thing they have to a logo. Some assets are here: https://golang.org/doc/gopher/ ([`gophercolor.png`](https://golang.org/doc/gopher/gophercolor.png) in particular looks nice) all of which are licensed CC-BY.

**Comment by mglukhovsky** [comment]
@encryptio: I think the reason we didn't use the Gopher is that he doesn't scale down well, so it looks fairly unattractive as an icon.

**Comment by encryptio** [comment]
Hmm. Now that I look at it, the [favicon for golang.org](https://golang.org/favicon.ico) (which works decently well, IMO) is a different image (just the gopher's head), and it's not in that folder.

**Comment by dalanmiller** [comment]
I vote for the golang.org favicon. I think part of the appeal of the Go
Gopher is his somewhat garish derpedness.

2015-12-14 15:02 GMT-08:00 Chris Kastorff <notifications@github.com>:

**Comment by chipotle** [comment]
Closed in #982
